const sevenDaySnapshot = {
  metrics: [
    { id: 'clicks', label: 'Clicks', value: '48,620', change: '+12.8%', note: 'vs previous period', tone: 'blue', icon: 'cursor' },
    { id: 'orders', label: 'Orders', value: '1,284', change: '+8.4%', note: 'completed orders', tone: 'cyan', icon: 'receipt' },
    { id: 'gross-sales', label: 'Gross sales', value: '$186,420.80', change: '+15.2%', note: 'before adjustments', tone: 'green', icon: 'dollar' },
    { id: 'net-sales', label: 'Net sales', value: '$172,840.30', change: '+11.6%', note: 'after returns & voids', tone: 'mint', icon: 'trend' },
    { id: 'commission', label: 'Commission', value: '$24,860.40', change: '+9.6%', note: 'approved this period', tone: 'purple', icon: 'coins' },
    { id: 'conversion', label: 'Conversion', value: '2.6%', change: '+0.3%', note: 'click-to-order rate', tone: 'sky', icon: 'chart' },
    { id: 'total-payout', label: 'Total payout', value: '$31,280.40', change: '+7.9%', note: 'commission + fees', tone: 'orange', icon: 'wallet' },
  ],
  partnerPerformance: [
    { id: 'partner-alpha', name: 'Partner Alpha', type: 'Publisher', amount: '$6,845.20', percent: 100, trend: '+18.4%', orders: '214' },
    { id: 'partner-beta', name: 'Partner Beta', type: 'Publisher', amount: '$5,126.80', percent: 75, trend: '+12.1%', orders: '186' },
    { id: 'partner-gamma', name: 'Partner Gamma', type: 'Influencer', amount: '$4,382.10', percent: 64, trend: '+7.8%', orders: '142' },
    { id: 'partner-delta', name: 'Partner Delta', type: 'Publisher', amount: '$3,614.60', percent: 53, trend: '+4.6%', orders: '118' },
    { id: 'partner-epsilon', name: 'Partner Epsilon', type: 'Influencer', amount: '$2,906.40', percent: 42, trend: '+2.9%', orders: '96' },
  ],
  commission: {
    total: '$49.7K',
    approved: { label: 'Approved', value: '$24,860', percent: 46, tone: 'green' },
    pending: { label: 'Pending approval', value: '$6,420', percent: 13, tone: 'orange' },
    paid: { label: 'Total paid', value: '$18,440', percent: 37, tone: 'blue' },
    voided: { label: 'Voided', value: '$1,280', percent: 4, tone: 'pink' },
  },
  partnerStatus: [
    { id: 'active', label: 'Active partners', value: 42, percent: 78, tone: 'green' },
    { id: 'applications', label: 'Applications pending', value: 12, percent: 22, tone: 'orange' },
    { id: 'invited', label: 'Invitations sent', value: 8, percent: 15, tone: 'blue' },
  ],
};

const thirtyDaySnapshot = {
  metrics: [
    { id: 'clicks', label: 'Clicks', value: '182,940', change: '+16.4%', note: 'vs previous period', tone: 'blue', icon: 'cursor' },
    { id: 'orders', label: 'Orders', value: '4,982', change: '+13.1%', note: 'completed orders', tone: 'cyan', icon: 'receipt' },
    { id: 'gross-sales', label: 'Gross sales', value: '$724,680.10', change: '+18.2%', note: 'before adjustments', tone: 'green', icon: 'dollar' },
    { id: 'net-sales', label: 'Net sales', value: '$681,240.70', change: '+14.4%', note: 'after returns & voids', tone: 'mint', icon: 'trend' },
    { id: 'commission', label: 'Commission', value: '$96,420.80', change: '+12.8%', note: 'approved this period', tone: 'purple', icon: 'coins' },
    { id: 'conversion', label: 'Conversion', value: '2.7%', change: '+0.4%', note: 'click-to-order rate', tone: 'sky', icon: 'chart' },
    { id: 'total-payout', label: 'Total payout', value: '$121,840.50', change: '+10.6%', note: 'commission + fees', tone: 'orange', icon: 'wallet' },
  ],
  partnerPerformance: [
    { id: 'partner-alpha', name: 'Partner Alpha', type: 'Publisher', amount: '$21,340.90', percent: 100, trend: '+20.6%', orders: '684' },
    { id: 'partner-beta', name: 'Partner Beta', type: 'Publisher', amount: '$16,820.40', percent: 79, trend: '+14.8%', orders: '596' },
    { id: 'partner-gamma', name: 'Partner Gamma', type: 'Influencer', amount: '$13,280.10', percent: 62, trend: '+11.2%', orders: '452' },
    { id: 'partner-delta', name: 'Partner Delta', type: 'Publisher', amount: '$10,460.80', percent: 49, trend: '+8.6%', orders: '390' },
    { id: 'partner-epsilon', name: 'Partner Epsilon', type: 'Influencer', amount: '$8,620.30', percent: 40, trend: '+5.4%', orders: '316' },
  ],
  commission: {
    total: '$194.2K',
    approved: { label: 'Approved', value: '$96,420', percent: 46, tone: 'green' },
    pending: { label: 'Pending approval', value: '$28,180', percent: 15, tone: 'orange' },
    paid: { label: 'Total paid', value: '$69,600', percent: 35, tone: 'blue' },
    voided: { label: 'Voided', value: '$4,280', percent: 4, tone: 'pink' },
  },
  partnerStatus: [
    { id: 'active', label: 'Active partners', value: 48, percent: 71, tone: 'green' },
    { id: 'applications', label: 'Applications pending', value: 16, percent: 24, tone: 'orange' },
    { id: 'invited', label: 'Invitations sent', value: 11, percent: 16, tone: 'blue' },
  ],
};

const ninetyDaySnapshot = {
  metrics: [
    { id: 'clicks', label: 'Clicks', value: '526,840', change: '+21.2%', note: 'vs previous period', tone: 'blue', icon: 'cursor' },
    { id: 'orders', label: 'Orders', value: '14,620', change: '+17.6%', note: 'completed orders', tone: 'cyan', icon: 'receipt' },
    { id: 'gross-sales', label: 'Gross sales', value: '$2.18M', change: '+24.9%', note: 'before adjustments', tone: 'green', icon: 'dollar' },
    { id: 'net-sales', label: 'Net sales', value: '$2.05M', change: '+20.3%', note: 'after returns & voids', tone: 'mint', icon: 'trend' },
    { id: 'commission', label: 'Commission', value: '$286.4K', change: '+19.8%', note: 'approved this period', tone: 'purple', icon: 'coins' },
    { id: 'conversion', label: 'Conversion', value: '2.8%', change: '+0.5%', note: 'click-to-order rate', tone: 'sky', icon: 'chart' },
    { id: 'total-payout', label: 'Total payout', value: '$362.8K', change: '+18.1%', note: 'commission + fees', tone: 'orange', icon: 'wallet' },
  ],
  partnerPerformance: [
    { id: 'partner-alpha', name: 'Partner Alpha', type: 'Publisher', amount: '$64,280.30', percent: 100, trend: '+24.2%', orders: '2,140' },
    { id: 'partner-beta', name: 'Partner Beta', type: 'Publisher', amount: '$51,620.40', percent: 80, trend: '+19.6%', orders: '1,864' },
    { id: 'partner-gamma', name: 'Partner Gamma', type: 'Influencer', amount: '$42,180.10', percent: 66, trend: '+16.2%', orders: '1,420' },
    { id: 'partner-delta', name: 'Partner Delta', type: 'Publisher', amount: '$32,460.80', percent: 50, trend: '+12.5%', orders: '1,080' },
    { id: 'partner-epsilon', name: 'Partner Epsilon', type: 'Influencer', amount: '$26,820.30', percent: 42, trend: '+9.6%', orders: '860' },
  ],
  commission: {
    total: '$582.8K',
    approved: { label: 'Approved', value: '$286,420', percent: 45, tone: 'green' },
    pending: { label: 'Pending approval', value: '$82,180', percent: 14, tone: 'orange' },
    paid: { label: 'Total paid', value: '$214,200', percent: 37, tone: 'blue' },
    voided: { label: 'Voided', value: '$11,280', percent: 4, tone: 'pink' },
  },
  partnerStatus: [
    { id: 'active', label: 'Active partners', value: 58, percent: 70, tone: 'green' },
    { id: 'applications', label: 'Applications pending', value: 21, percent: 25, tone: 'orange' },
    { id: 'invited', label: 'Invitations sent', value: 15, percent: 18, tone: 'blue' },
  ],
};

export const dashboardData = {
  workspace: {
    organization: 'YeahPromos',
    brand: 'Demo Brand',
    store: 'Demo Store',
    role: 'Demo Admin',
    currency: 'USD',
    timezone: 'America/Los_Angeles',
  },
  periods: [
    { id: '7d', label: 'May 05 – May 12, 2025', shortLabel: 'Last 7 days', snapshot: sevenDaySnapshot },
    { id: '30d', label: 'Apr 13 – May 12, 2025', shortLabel: 'Last 30 days', snapshot: thirtyDaySnapshot },
    { id: '90d', label: 'Feb 12 – May 12, 2025', shortLabel: 'Last 90 days', snapshot: ninetyDaySnapshot },
  ],
  navigation: [
    { id: 'overview', label: 'Overview', icon: 'grid' },
    {
      id: 'recruitment',
      label: 'Recruitment & Partners',
      icon: 'users',
      children: [
        { id: 'discover-influencers', label: 'Discover influencers' },
        { id: 'discover-publishers', label: 'Discover publishers' },
        { id: 'my-partners', label: 'My partners' },
        { id: 'applications', label: 'Applications' },
        { id: 'invite-history', label: 'Invite history' },
      ],
    },
    {
      id: 'campaigns',
      label: 'Campaigns',
      icon: 'chart',
      children: [
        { id: 'all-campaigns', label: 'All campaigns' },
        { id: 'affiliate-programs', label: 'Affiliate programs' },
        { id: 'influencer-campaigns', label: 'Influencer campaigns' },
      ],
    },
    {
      id: 'products-assets',
      label: 'Products & Assets',
      icon: 'bag',
      children: [
        { id: 'product-feed', label: 'Product feed' },
        { id: 'coupons', label: 'Coupons' },
        { id: 'banners-images', label: 'Banners & images' },
        { id: 'videos', label: 'Videos' },
      ],
    },
    {
      id: 'commission-rules',
      label: 'Commission & Rules',
      icon: 'coins',
      children: [
        { id: 'commission-rules-list', label: 'Commission rules' },
        { id: 'attribution-rules', label: 'Attribution rules' },
        { id: 'restriction-rules', label: 'Restriction rules' },
        { id: 'ppc', label: 'PPC' },
      ],
    },
    {
      id: 'data-transactions',
      label: 'Data & Transactions',
      icon: 'trend',
      children: [
        { id: 'performance', label: 'Performance' },
        { id: 'performance-brand', label: 'Performance by brand' },
        { id: 'transactions', label: 'Transactions' },
        { id: 'amazon-brb', label: 'Amazon BRB' },
      ],
    },
    {
      id: 'finance',
      label: 'Finance',
      icon: 'wallet',
      children: [
        { id: 'balance-payments', label: 'Balance & payments' },
        { id: 'transaction-history', label: 'Transaction history' },
        { id: 'payouts', label: 'Payouts' },
        { id: 'invoices', label: 'Invoices' },
        { id: 'payment-methods', label: 'Payment methods' },
      ],
    },
    {
      id: 'messages',
      label: 'Messages & Notifications',
      icon: 'message',
      children: [
        { id: 'all-messages', label: 'All Messages' },
        { id: 'partner-messages', label: 'Partner Messages' },
        { id: 'system-alerts', label: 'System Alerts' },
        { id: 'archived-messages', label: 'Archived' },
      ],
    },
    {
      id: 'settings',
      label: 'Integrations & Settings',
      icon: 'settings',
      children: [
        { id: 'team-accounts', label: 'Team accounts' },
        { id: 'permissions', label: 'Permissions' },
        { id: 'recruitment-page', label: 'Recruitment page' },
        { id: 'brand-integration', label: 'Brand integration' },
        { id: 'api-credentials', label: 'API credentials' },
      ],
    },
  ],
  ...sevenDaySnapshot,
  lastUpdated: '4 min ago',
  actionItems: [
    {
      id: 'application-review',
      icon: 'users',
      tone: 'blue',
      eyebrow: 'Partner applications',
      title: '12 applications need review',
      description: 'New publisher channels are waiting for approval.',
      meta: '12 pending',
      action: 'Review applications',
      navigationId: 'applications',
    },
    {
      id: 'product-sync',
      icon: 'bag',
      tone: 'orange',
      eyebrow: 'Product feed sync',
      title: '3 products failed to sync',
      description: 'Review the ASIN errors before the next campaign launch.',
      meta: 'Sync failed',
      action: 'View errors',
      navigationId: 'product-feed',
    },
    {
      id: 'campaign-launch',
      icon: 'chart',
      tone: 'purple',
      eyebrow: 'Campaigns',
      title: 'Summer Sale starts in 5 days',
      description: 'Confirm offers, creatives and partner access before launch.',
      meta: 'Scheduled',
      action: 'Open campaign',
      navigationId: 'all-campaigns',
    },
    {
      id: 'transaction-approval',
      icon: 'receipt',
      tone: 'green',
      eyebrow: 'Transactions',
      title: '28 transactions are ready for approval',
      description: 'Approve or void transactions with a reason and audit trail.',
      meta: '28 pending',
      action: 'Review transactions',
      navigationId: 'transactions',
    },
  ],
  quickActions: [
    { id: 'invite-partner', icon: 'send', label: 'Invite partner', navigationId: 'invite-history' },
    { id: 'create-campaign', icon: 'chart', label: 'Create campaign', navigationId: 'all-campaigns' },
    { id: 'add-product', icon: 'bag', label: 'Add product', navigationId: 'product-feed' },
    { id: 'add-coupon', icon: 'tag', label: 'Add coupon', navigationId: 'coupons' },
    { id: 'export-report', icon: 'download', label: 'Export report', navigationId: 'performance' },
  ],
  partners: [
    {
      id: 'northstar',
      name: 'Alpha Media',
      type: 'Publisher',
      channel: 'Content/Blog',
      status: 'Active',
      group: 'Premium publishers',
      audience: '1.2M monthly visits',
      commission: '$2,812.45',
    },
  ],
};


export const campaignPageData = {
  metrics: [
    { id: 'active-campaigns', label: 'Active campaigns', value: '18', change: '↑ 12.5%', note: 'vs Apr 28 – May 04', icon: 'users', sparkline: '0,26 12,18 25,31 37,16 48,25 60,10 71,17 84,12 96,6' },
    { id: 'click-throughs', label: 'Click-throughs', value: '282,401', change: '↑ 8.2%', note: 'vs Apr 28 – May 04', icon: 'cursor', sparkline: '0,25 12,18 25,31 36,17 48,24 60,7 72,14 84,4 96,10' },
    { id: 'campaign-orders', label: 'Orders', value: '6,521', change: '↑ 11.6%', note: 'vs Apr 28 – May 04', icon: 'receipt', sparkline: '0,23 12,16 24,29 36,19 47,26 60,9 70,15 84,5 96,9' },
    { id: 'campaign-sales', label: 'Sales', value: '$327,128.54', change: '↑ 9.7%', note: 'vs Apr 28 – May 04', icon: 'dollar', sparkline: '0,26 12,21 24,29 36,11 48,23 60,7 71,15 84,4 96,8' },
  ],
  campaigns: [
    {
      id: 'spring-collection-promo',
      name: 'Spring Collection Promo',
      code: 'CMP-2024-0001',
      type: 'Co-op',
      typeIcon: 'users',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Active',
      statusDetail: 'On track',
      stage: 'Execution',
      partners: '24',
      sales: '$62,845.22',
      orders: '32 orders',
      progress: 68,
      nextAction: 'Review assets',
      nextActionIcon: 'calendar',
      updated: 'May 16, 2025',
      updatedBy: 'Demo Owner A',
    },
    {
      id: 'tech-essentials-launch',
      name: 'Tech Essentials Launch',
      code: 'CMP-2024-0002',
      type: 'MDF',
      typeIcon: 'coins',
      channel: 'Influencer',
      channelIcon: 'users',
      status: 'Pending',
      statusDetail: 'Awaiting approval',
      stage: 'Review',
      partners: '18',
      sales: '$44,318.19',
      orders: '892 orders',
      progress: 15,
      nextAction: 'Approve budget',
      nextActionIcon: 'users',
      updated: 'May 15, 2025',
      updatedBy: 'Demo Owner B',
    },
    {
      id: 'mothers-day-special',
      name: "Mother's Day Special",
      code: 'CMP-2024-0003',
      type: 'Event',
      typeIcon: 'calendar',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Completed',
      statusDetail: 'Completed',
      stage: 'Complete',
      partners: '36',
      sales: '$38,912.46',
      orders: '768 orders',
      progress: 100,
      nextAction: 'No action required',
      nextActionIcon: 'check',
      updated: 'May 10, 2025',
      updatedBy: 'Demo Owner A',
    },
    {
      id: 'summer-sale-kickoff',
      name: 'Summer Sale Kickoff',
      code: 'CMP-2024-0004',
      type: 'Enablement',
      typeIcon: 'bag',
      channel: 'Publisher',
      channelIcon: 'send',
      status: 'Paused',
      statusDetail: 'Paused',
      stage: 'Execution',
      partners: '21',
      sales: '$28,433.71',
      orders: '543 orders',
      progress: 40,
      nextAction: 'Resume campaign',
      nextActionIcon: 'arrow',
      updated: 'May 9, 2025',
      updatedBy: 'Demo Owner B',
    },
    {
      id: 'back-to-school',
      name: 'Back to School',
      code: 'CMP-2024-0005',
      type: 'Co-op',
      typeIcon: 'users',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Draft',
      statusDetail: 'In planning',
      stage: 'Planning',
      partners: '12',
      sales: '$21,247.88',
      orders: '412 orders',
      progress: 30,
      nextAction: 'Add campaign assets',
      nextActionIcon: 'bag',
      updated: 'May 8, 2025',
      updatedBy: 'Demo Owner C',
    },
    {
      id: 'holiday-gift-guide',
      name: 'Holiday Gift Guide',
      code: 'CMP-2024-0006',
      type: 'MDF',
      typeIcon: 'coins',
      channel: 'Influencer',
      channelIcon: 'users',
      status: 'Closed',
      statusDetail: 'Completed',
      stage: 'Complete',
      partners: '15',
      sales: '$0',
      orders: '0 orders',
      progress: 100,
      nextAction: 'No action required',
      nextActionIcon: 'check',
      updated: 'May 6, 2025',
      updatedBy: 'Demo Owner C',
    },
    {
      id: 'brand-awareness-q2',
      name: 'Brand Awareness Q2',
      code: 'CMP-2024-0007',
      type: 'Event',
      typeIcon: 'calendar',
      channel: 'Publisher',
      channelIcon: 'send',
      status: 'Active',
      statusDetail: 'On track',
      stage: 'Execution',
      partners: '31',
      sales: '$33,614.93',
      orders: '678 orders',
      progress: 52,
      nextAction: 'Confirm attendance',
      nextActionIcon: 'calendar',
      updated: 'May 5, 2025',
      updatedBy: 'Demo Owner A',
    },
    {
      id: 'flash-sale-weekend',
      name: 'Flash Sale Weekend',
      code: 'CMP-2024-0008',
      type: 'Enablement',
      typeIcon: 'bag',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Completed',
      statusDetail: 'Completed',
      stage: 'Complete',
      partners: '9',
      sales: '$15,362.15',
      orders: '312 orders',
      progress: 100,
      nextAction: 'No action required',
      nextActionIcon: 'check',
      updated: 'May 4, 2025',
      updatedBy: 'Demo Owner B',
    },
  ],
};

export const attributionPageData = {
  models: [
    {
      id: 'data-driven',
      label: 'Data-driven (recommended)',
      summaryLabel: 'Data-driven model',
      description: 'Data-driven model analyzes historical performance to determine the optimal credit distribution across touchpoints.',
    },
    {
      id: 'last-click',
      label: 'Last-click',
      summaryLabel: 'Last-click model',
      description: 'Last-click model assigns conversion credit to the final eligible touchpoint before purchase.',
    },
    {
      id: 'first-click',
      label: 'First-click',
      summaryLabel: 'First-click model',
      description: 'First-click model assigns conversion credit to the first eligible touchpoint in the journey.',
    },
    {
      id: 'linear',
      label: 'Linear',
      summaryLabel: 'Linear model',
      description: 'Linear model distributes conversion credit evenly across eligible touchpoints.',
    },
    {
      id: 'position-based',
      label: 'Position-based (U-shape)',
      summaryLabel: 'Position-based model',
      description: 'Position-based model gives more credit to the first and last eligible touchpoints.',
    },
  ],
  activeModel: 'data-driven',
  summary: {
    assistedRevenue: '$128,430.76',
    trackingCoverage: '88.7%',
  },
  distribution: [
    { id: 'last-click', label: 'Last-click', value: 40, icon: 'users', tone: 'coral' },
    { id: 'direct-publisher', label: 'Direct publisher', value: 30, icon: 'send', tone: 'orange' },
    { id: 'influencer', label: 'Influencer', value: 20, icon: 'star', tone: 'purple' },
    { id: 'paid-media', label: 'Paid media', value: 10, icon: 'trend', tone: 'blue' },
  ],
  rules: [
    { id: 'main-website-blog', name: 'Main Website & Blog', channelType: 'Publisher', channelTone: 'publisher', logic: 'Last-click within channel', lookback: '30 days', priority: 1, status: 'Active' },
    { id: 'partner-content-reviews', name: 'Partner Content & Reviews', channelType: 'Publisher', channelTone: 'publisher', logic: 'Data-driven (weighted)', lookback: '30 days', priority: 2, status: 'Active' },
    { id: 'influencer-social-traffic', name: 'Influencer Social Traffic', channelType: 'Influencer', channelTone: 'influencer', logic: 'First-click within channel', lookback: '14 days', priority: 3, status: 'Active' },
    { id: 'influencer-promo-codes', name: 'Influencer Promo Codes', channelType: 'Influencer', channelTone: 'influencer', logic: 'Last-click within channel', lookback: '30 days', priority: 4, status: 'Active' },
    { id: 'paid-search-campaigns', name: 'Paid Search Campaigns', channelType: 'Paid', channelTone: 'paid', logic: 'Last-click', lookback: '7 days', priority: 5, status: 'Active' },
    { id: 'paid-social-campaigns', name: 'Paid Social Campaigns', channelType: 'Paid', channelTone: 'paid', logic: 'Position-based (U-shape)', lookback: '7 days', priority: 6, status: 'Active' },
  ],
  audit: [
    { id: 'lookback-update', date: 'May 12, 2025, 10:24 AM', title: 'Updated lookback window for Influencer Social Traffic', by: 'Demo Admin' },
    { id: 'paid-social-rule', date: 'May 9, 2025, 3:18 PM', title: 'Added rule: Paid Social Campaigns', by: 'Demo Admin' },
    { id: 'model-change', date: 'May 5, 2025, 9:41 AM', title: 'Changed attribution model to Data-driven', by: 'Demo Admin' },
    { id: 'initial-rules', date: 'Apr 28, 2025, 2:11 PM', title: 'Initial attribution rules created', by: 'Demo Admin' },
  ],
};

export const couponAttributionPageData = {
  demoOnly: true,
  metrics: [
    { id: 'active-rules', label: 'Active coupon rules', value: '6', note: '4 partner-owned rules', icon: 'tag', tone: 'coral' },
    { id: 'attributed-orders', label: 'Coupon-attributed orders', value: '428', note: '31.6% of tracked orders', icon: 'receipt', tone: 'purple' },
    { id: 'pending-conflicts', label: 'Pending conflicts', value: '3', note: 'Need merchant review', icon: 'clock', tone: 'orange' },
    { id: 'attributed-sales', label: 'Attributed sales', value: '$38,240.10', note: 'May 05 – May 12, 2025', icon: 'dollar', tone: 'green' },
  ],
  selectedRuleId: 'partner-owned-code',
  rules: [
    {
      id: 'partner-owned-code',
      ruleId: 'CA-1001',
      name: 'Partner-owned coupon code',
      couponScope: 'Unique partner codes',
      scopeTone: 'partner',
      matchType: 'Exact code match',
      priority: '1',
      fallback: 'No fallback',
      lookback: '30 days click',
      conflict: 'Primary signal',
      status: 'Active',
      statusTone: 'active',
      lastUpdated: 'May 12, 2025',
    },
    {
      id: 'coupon-with-link',
      ruleId: 'CA-1004',
      name: 'Coupon plus partner link',
      couponScope: 'Partner campaign codes',
      scopeTone: 'partner',
      matchType: 'Coupon + eligible click',
      priority: '2',
      fallback: 'Keep coupon owner',
      lookback: '30 days click',
      conflict: 'Assisted link only',
      status: 'Active',
      statusTone: 'active',
      lastUpdated: 'May 10, 2025',
    },
    {
      id: 'public-campaign-code',
      ruleId: 'CA-1007',
      name: 'Public campaign coupon',
      couponScope: 'Public campaign codes',
      scopeTone: 'public',
      matchType: 'Code with no owner',
      priority: '3',
      fallback: 'Use eligible click',
      lookback: '30 days click',
      conflict: 'Link fallback',
      status: 'Active',
      statusTone: 'active',
      lastUpdated: 'May 08, 2025',
    },
    {
      id: 'expired-code-fallback',
      ruleId: 'CA-1010',
      name: 'Expired code fallback',
      couponScope: 'Expired or invalid codes',
      scopeTone: 'exception',
      matchType: 'Invalid code',
      priority: '4',
      fallback: 'Ignore code, use click',
      lookback: '30 days click',
      conflict: 'Log exception',
      status: 'Active',
      statusTone: 'active',
      lastUpdated: 'May 06, 2025',
    },
    {
      id: 'multiple-code-review',
      ruleId: 'CA-1013',
      name: 'Multiple coupon conflict',
      couponScope: 'Two or more owned codes',
      scopeTone: 'exception',
      matchType: 'Multiple exact matches',
      priority: '5',
      fallback: 'Hold for review',
      lookback: 'Order-level',
      conflict: 'Manual resolution',
      status: 'Pending',
      statusTone: 'pending',
      lastUpdated: 'May 05, 2025',
    },
    {
      id: 'direct-public-code',
      ruleId: 'CA-1016',
      name: 'Direct public code',
      couponScope: 'Public code without referral',
      scopeTone: 'public',
      matchType: 'No eligible touch',
      priority: '6',
      fallback: 'No partner credit',
      lookback: 'Not applicable',
      conflict: 'No commission',
      status: 'Inactive',
      statusTone: 'inactive',
      lastUpdated: 'Apr 28, 2025',
    },
  ],
  details: {
    'partner-owned-code': {
      description: 'A valid, active coupon code owned by a partner is the primary attribution signal for the order.',
      decision: '100% of eligible partner commission goes to the coupon owner.',
      scope: 'Partner-owned codes · Eligible products',
      lookback: '30 days click / 1 day view',
      effectiveDate: 'May 01, 2025',
      lastUpdated: 'May 12, 2025 by Demo Admin',
      decisionOrder: [
        'Validate the coupon code, campaign, product scope, and order status.',
        'Match an exact active code to one partner owner; the owner receives primary credit.',
        'Keep a qualifying referral click as assisted context, but do not pay a second commission.',
        'If the code is invalid or expired, ignore it and fall back to the most recent eligible click.',
      ],
      conflicts: [
        'Two or more partner-owned codes on one order are held for manual review; no commission is finalized.',
        'A public code without an eligible partner touch does not create partner commission.',
        'Cancelled, fully refunded, or out-of-scope orders are excluded and recorded in the audit log.',
      ],
      audit: 'Every decision stores order ID, coupon code, partner UID, matched rule, fallback reason, and timestamp.',
    },
    'coupon-with-link': {
      description: 'When a partner coupon and an eligible referral link are both present, coupon ownership wins.',
      decision: 'Coupon owner receives primary credit; the link partner is marked assisted.',
      scope: 'Partner campaign codes · Partner links',
      lookback: '30 days click / 1 day view',
      effectiveDate: 'May 01, 2025',
      lastUpdated: 'May 10, 2025 by Demo Admin',
      decisionOrder: [
        'Confirm the code belongs to an active partner and the link event is inside the lookback window.',
        'Assign primary credit to the coupon owner and preserve the link as an assisted touch.',
        'Apply the linked commission rule once; never stack two primary commissions for one order.',
      ],
      conflicts: [
        'If the code is not owned by a partner, continue with the eligible click fallback.',
        'If the click is outside the window, it is retained for reporting but cannot receive credit.',
      ],
      audit: 'The audit record stores both the primary coupon match and the assisted link touch.',
    },
  },
  filters: {
    status: ['all', 'Active', 'Pending', 'Inactive'],
    couponScope: ['all', 'Unique partner codes', 'Partner campaign codes', 'Public campaign codes', 'Expired or invalid codes'],
    matchType: ['all', 'Exact code match', 'Coupon + eligible click', 'Code with no owner', 'Invalid code', 'Multiple exact matches', 'No eligible touch'],
    conflict: ['all', 'Primary signal', 'Assisted link only', 'Link fallback', 'Log exception', 'Manual resolution', 'No commission'],
  },
  audit: [
    { id: 'multiple-code-review', date: 'May 12, 2025, 10:24 AM', title: 'Sent multiple-code conflict to manual review', by: 'Demo Admin' },
    { id: 'coupon-link-update', date: 'May 10, 2025, 3:18 PM', title: 'Clarified coupon plus partner link precedence', by: 'Demo Admin' },
    { id: 'fallback-rule', date: 'May 6, 2025, 9:41 AM', title: 'Added invalid-code click fallback', by: 'Demo Admin' },
  ],
};

export const commissionRulesPageData = {
  metrics: [
    { id: 'active-rules', label: 'Active rules', value: '18', note: '12 added this month', icon: 'check', tone: 'coral' },
    { id: 'partners-covered', label: 'Partners covered', value: '1,248', note: '↑ 82% of total partners', icon: 'users', tone: 'purple' },
    { id: 'pending-changes', label: 'Pending changes', value: '3', note: '↑ 2 awaiting approval', icon: 'receipt', tone: 'orange' },
  ],
  selectedRuleId: 'standard-content-commission',
  rules: [
    {
      id: 'standard-content-commission',
      ruleId: 'ID: 10234',
      name: 'Standard Content Commission',
      scopePrimary: 'All partners',
      scopeSecondary: 'All products',
      scopeSummary: 'All partners / All products',
      partnerType: 'All partners',
      channel: 'Affiliate',
      baseCommission: '8.00%',
      rate: '8.00%',
      unit: '%',
      bonusRate: '2.00%',
      bonusThreshold: 'Over $500',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'May 01, 2025',
      effectiveAt: '2025-05-01',
      lastUpdated: 'Apr 30, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'new-partner-boost',
      ruleId: 'ID: 10231',
      name: 'New Partner Boost',
      scopePrimary: 'New partners',
      scopeSecondary: 'All products',
      scopeSummary: 'New partners / All products',
      partnerType: 'New partners',
      channel: 'Affiliate',
      baseCommission: '10.00%',
      rate: '10.00%',
      unit: '%',
      bonusRate: '3.00%',
      bonusThreshold: 'Over $300',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'Apr 15, 2025',
      effectiveAt: '2025-04-15',
      lastUpdated: 'Apr 14, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'seasonal-sale-bonus',
      ruleId: 'ID: 10228',
      name: 'Seasonal Sale Bonus',
      scopePrimary: 'All partners',
      scopeSecondary: 'Sale collection',
      scopeSummary: 'All partners / Sale collection',
      partnerType: 'All partners',
      channel: 'Affiliate',
      baseCommission: '6.00%',
      rate: '6.00%',
      unit: '%',
      bonusRate: '5.00%',
      bonusThreshold: 'Over $400',
      attributionWindow: '7 days',
      attributionType: 'Click',
      duration: '7 days',
      effectiveDate: 'Apr 10, 2025',
      effectiveAt: '2025-04-10',
      lastUpdated: 'Apr 9, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'blog-content-partners',
      ruleId: 'ID: 10225',
      name: 'Blog & Content Partners',
      scopePrimary: 'Content / Blog',
      scopeSecondary: 'All products',
      scopeSummary: 'Content / Blog / All products',
      partnerType: 'Content / Blog',
      channel: 'Publisher',
      baseCommission: '9.00%',
      rate: '9.00%',
      unit: '%',
      bonusRate: '2.00%',
      bonusThreshold: 'Over $500',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'Mar 25, 2025',
      effectiveAt: '2025-03-25',
      lastUpdated: 'Mar 24, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'tech-review-partners',
      ruleId: 'ID: 10221',
      name: 'Tech Review Partners',
      scopePrimary: 'Technology',
      scopeSecondary: 'All products',
      scopeSummary: 'Technology / All products',
      partnerType: 'Technology',
      channel: 'Publisher',
      baseCommission: '7.00%',
      rate: '7.00%',
      unit: '%',
      bonusRate: '2.00%',
      bonusThreshold: 'Over $600',
      attributionWindow: '14 days',
      attributionType: 'Click',
      duration: '14 days',
      effectiveDate: 'Mar 20, 2025',
      effectiveAt: '2025-03-20',
      lastUpdated: 'Mar 19, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'newsletter-partners',
      ruleId: 'ID: 10218',
      name: 'Newsletter Partners',
      scopePrimary: 'Email / Newsletter',
      scopeSecondary: 'All products',
      scopeSummary: 'Email / Newsletter / All products',
      partnerType: 'Email / Newsletter',
      channel: 'Email',
      baseCommission: '10.00%',
      rate: '10.00%',
      unit: '%',
      bonusRate: '1.00%',
      bonusThreshold: 'Over $250',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'Mar 10, 2025',
      effectiveAt: '2025-03-10',
      lastUpdated: 'Mar 9, 2025',
      status: 'Scheduled',
      statusTone: 'scheduled',
    },
    {
      id: 'inactive-old-rules',
      ruleId: 'ID: 10198',
      name: 'Inactive – Old Rules',
      scopePrimary: 'All partners',
      scopeSecondary: 'All products',
      scopeSummary: 'All partners / All products',
      partnerType: 'All partners',
      channel: 'Affiliate',
      baseCommission: '5.00%',
      rate: '5.00%',
      unit: '%',
      bonusRate: '—',
      bonusThreshold: '',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'Feb 01, 2025',
      effectiveAt: '2025-02-01',
      lastUpdated: 'Jan 31, 2025',
      status: 'Inactive',
      statusTone: 'inactive',
    },
    {
      id: 'black-friday-bonus',
      ruleId: 'ID: 10176',
      name: 'Black Friday Bonus',
      scopePrimary: 'All partners',
      scopeSecondary: 'BF collection',
      scopeSummary: 'All partners / BF collection',
      partnerType: 'All partners',
      channel: 'Affiliate',
      baseCommission: '8.00%',
      rate: '8.00%',
      unit: '%',
      bonusRate: '6.00%',
      bonusThreshold: 'Over $500',
      attributionWindow: '7 days',
      attributionType: 'Click',
      duration: '7 days',
      effectiveDate: 'Nov 15, 2024',
      effectiveAt: '2024-11-15',
      lastUpdated: 'Nov 14, 2024',
      status: 'Expired',
      statusTone: 'expired',
    },
  ],
  details: {
    'standard-content-commission': {
      description: 'Applies to all partners across all products and channels.',
      scope: 'All partners · All products',
      attributionWindow: '30 days',
      attributionType: 'Click',
      effectiveDate: 'May 01, 2025',
      lastUpdated: 'Apr 30, 2025',
      updatedBy: 'Demo Admin',
      tiers: [
        { label: 'Tier 1', amount: '$0.00 – $199.99', base: '6.00%', bonus: '—' },
        { label: 'Tier 2', amount: '$200.00 – $499.99', base: '7.00%', bonus: '1.00%' },
        { label: 'Tier 3', amount: '$500.00 – $999.99', base: '8.00%', bonus: '2.00%' },
        { label: 'Tier 4', amount: '$1,000.00+', base: '9.00%', bonus: '3.00%' },
      ],
      conditions: [
        'Valid for Content / Blog, Technology, and Review partners',
        'Excludes coupon-based orders',
      ],
      performance: {
        period: 'May 01 – May 12, 2025',
        clicks: '12,842',
        conversions: '1,024',
        commission: '$1,248.36',
      },
    },
  },
};

export const restrictionRulesPageData = {
  metrics: [
    { id: 'active-restrictions', label: 'Active restrictions', value: '6', note: '2 brand terms protected', icon: 'shield', tone: 'coral' },
    { id: 'partners-covered', label: 'Partners covered', value: '842', note: 'Across 5 channels', icon: 'users', tone: 'purple' },
    { id: 'pending-review', label: 'Pending review', value: '2', note: 'Need policy confirmation', icon: 'clock', tone: 'orange' },
  ],
  selectedRuleId: 'brand-search-protection',
  rules: [
    {
      id: 'brand-search-protection',
      ruleId: 'PPC-2041',
      name: 'Brand Search Protection',
      policy: 'Block',
      policyTone: 'blocked',
      termsSummary: 'YeahPromos, Yeah Promos',
      keywordCount: '2 brand terms',
      channel: 'Paid search',
      region: 'All regions',
      partnerScope: 'All partners',
      effectiveDate: 'May 01, 2025',
      effectiveAt: '2025-05-01',
      lastUpdated: 'Apr 30, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'generic-keyword-coverage',
      ruleId: 'PPC-2038',
      name: 'Generic Keyword Coverage',
      policy: 'Allow',
      policyTone: 'allowed',
      termsSummary: 'Non-brand product terms',
      keywordCount: '18 approved terms',
      channel: 'Google Ads',
      region: 'US, CA, UK',
      partnerScope: 'Approved partners',
      effectiveDate: 'Apr 15, 2025',
      effectiveAt: '2025-04-15',
      lastUpdated: 'Apr 14, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'competitor-terms',
      ruleId: 'PPC-2035',
      name: 'Competitor Terms',
      policy: 'Block',
      policyTone: 'blocked',
      termsSummary: 'Competitor brand names',
      keywordCount: '12 blocked terms',
      channel: 'Paid search',
      region: 'North America',
      partnerScope: 'All partners',
      effectiveDate: 'Apr 10, 2025',
      effectiveAt: '2025-04-10',
      lastUpdated: 'Apr 09, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'coupon-search-traffic',
      ruleId: 'PPC-2028',
      name: 'Coupon Search Traffic',
      policy: 'Review',
      policyTone: 'review',
      termsSummary: 'Coupon and promo terms',
      keywordCount: '9 review terms',
      channel: 'Paid search',
      region: 'US, UK',
      partnerScope: 'Coupon partners',
      effectiveDate: 'Apr 01, 2025',
      effectiveAt: '2025-04-01',
      lastUpdated: 'Mar 31, 2025',
      status: 'Pending',
      statusTone: 'pending',
    },
    {
      id: 'paid-social-coverage',
      ruleId: 'PPC-2022',
      name: 'Paid Social Coverage',
      policy: 'Allow',
      policyTone: 'allowed',
      termsSummary: 'Approved campaign terms',
      keywordCount: '5 campaign terms',
      channel: 'Meta / TikTok',
      region: 'North America',
      partnerScope: 'Influencer group',
      effectiveDate: 'Mar 20, 2025',
      effectiveAt: '2025-03-20',
      lastUpdated: 'Mar 19, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'holiday-search-exception',
      ruleId: 'PPC-2017',
      name: 'Holiday Search Exception',
      policy: 'Allow',
      policyTone: 'allowed',
      termsSummary: 'Holiday campaign terms',
      keywordCount: '7 seasonal terms',
      channel: 'Google Ads',
      region: 'All regions',
      partnerScope: 'Approved partners',
      effectiveDate: 'Nov 15, 2024',
      effectiveAt: '2024-11-15',
      lastUpdated: 'Nov 14, 2024',
      status: 'Inactive',
      statusTone: 'inactive',
    },
    {
      id: 'legacy-publisher-policy',
      ruleId: 'PPC-2011',
      name: 'Legacy Publisher Policy',
      policy: 'Block',
      policyTone: 'blocked',
      termsSummary: 'Publisher exact-match terms',
      keywordCount: '4 blocked terms',
      channel: 'Paid search',
      region: 'All regions',
      partnerScope: 'Content / Blog',
      effectiveDate: 'Jan 01, 2025',
      effectiveAt: '2025-01-01',
      lastUpdated: 'Dec 31, 2024',
      status: 'Expired',
      statusTone: 'expired',
    },
  ],
  details: {
    'brand-search-protection': {
      description: 'Prevent partners from bidding on YeahPromos brand terms or sending paid traffic directly to the store.',
      enforcement: 'Block and review',
      keywords: ['YeahPromos', 'Yeah Promos'],
      channels: ['Google Ads', 'Microsoft Ads'],
      regions: 'All regions',
      partnerScope: 'All partners',
      effectiveDate: 'May 01, 2025',
      lastUpdated: 'Apr 30, 2025',
      updatedBy: 'Demo Admin',
      violations: '3 flagged this month',
      conditions: [
        'Exact and phrase matches for protected brand terms are blocked',
        'Direct-to-site PPC traffic is not permitted for partner links',
        'Partners must use approved non-brand keywords for paid search',
      ],
    },
  },
};

export const ppcPageData = {
  ...restrictionRulesPageData,
  rules: restrictionRulesPageData.rules.map((rule) => ({
    ...rule,
    matchType: rule.matchType ?? (rule.policy === 'Block' ? 'Exact + phrase match' : rule.policy === 'Allow' ? 'Broad + phrase match' : 'Phrase match'),
    violationAction: rule.violationAction ?? (rule.policy === 'Block' ? 'Block traffic and notify partner' : rule.policy === 'Review' ? 'Hold for merchant review' : 'Record and monitor traffic'),
  })),
  details: {
    ...restrictionRulesPageData.details,
    'brand-search-protection': {
      ...restrictionRulesPageData.details['brand-search-protection'],
      matchType: 'Exact + phrase match',
      violationAction: 'Block traffic and notify partner',
    },
  },
  businessRules: {
    precedence: [
      { title: 'Most specific match wins', description: 'Partner + campaign + region rules override broader channel or global rules.' },
      { title: 'Block overrides Allow', description: 'At the same scope, a Block decision wins over Allow; Review pauses final approval.' },
      { title: 'Undefined brand terms default to Block', description: 'New brand and competitor terms are protected until a merchant explicitly allows them.' },
      { title: 'Escalate evidence gaps', description: 'Missing landing-page or keyword evidence is Review, never an automatic approval.' },
    ],
    audit: 'Each decision stores the keyword, channel, region, partner, landing page, rule ID, action, and timestamp.',
  },
};

export const financeBalancePageData = {
  demoOnly: true,
  summary: [
    { id: 'account-balance', label: 'Account balance', value: '$20,062.51', note: '↑ 8.7% vs last 7 days', icon: 'wallet', tone: 'coral', noteTone: 'positive' },
    { id: 'available-payout', label: 'Available for payout', value: '$16,724.38', note: '↑ 5.3% vs last 7 days', icon: 'dollar', tone: 'green', noteTone: 'positive' },
    { id: 'pending-commission', label: 'Pending commission', value: '$5,059.44', note: 'From in-progress transactions', icon: 'clock', tone: 'purple', noteTone: 'neutral' },
    { id: 'next-payout-date', label: 'Next payout date', value: 'May 15, 2025', note: 'In 3 days', icon: 'calendar', tone: 'orange', noteTone: 'neutral' },
    { id: 'primary-payout-method', label: 'Primary payout method', value: '•••• 0000', note: 'Visa · Expires 05/27', icon: 'card', tone: 'blue', noteTone: 'neutral' },
  ],
  trend: {
    periods: {
      '30d': {
        label: 'Last 30 days',
        points: [
          { label: 'Apr 15', value: 14982 },
          { label: 'Apr 18', value: 14262 },
          { label: 'Apr 21', value: 13900 },
          { label: 'Apr 23', value: 8700 },
          { label: 'Apr 25', value: 10500 },
          { label: 'Apr 27', value: 12100 },
          { label: 'Apr 29', value: 15300 },
          { label: 'Apr 30', value: 14600 },
          { label: 'May 02', value: 16300 },
          { label: 'May 05', value: 13600 },
          { label: 'May 07', value: 15800 },
          { label: 'May 10', value: 17650 },
          { label: 'May 12', value: 20062 },
        ],
        tooltip: { index: 7, value: '$18,645.23' },
        yAxis: ['$25K', '$20K', '$15K', '$10K', '$5K', '$0'],
        xAxis: ['Apr 15', 'Apr 20', 'Apr 25', 'Apr 30', 'May 05', 'May 10'],
      },
      '90d': {
        label: 'Last 90 days',
        points: [
          { label: 'Feb 15', value: 11800 },
          { label: 'Mar 01', value: 12750 },
          { label: 'Mar 15', value: 13400 },
          { label: 'Apr 01', value: 14600 },
          { label: 'Apr 15', value: 14982 },
          { label: 'May 01', value: 17600 },
          { label: 'May 12', value: 20062 },
        ],
        tooltip: { index: 4, value: '$18,645.23' },
        yAxis: ['$25K', '$20K', '$15K', '$10K', '$5K', '$0'],
        xAxis: ['Feb 15', 'Mar 01', 'Mar 15', 'Apr 01', 'Apr 15', 'May 12'],
      },
      year: {
        label: 'This year',
        points: [
          { label: 'Jan', value: 9800 },
          { label: 'Feb', value: 11800 },
          { label: 'Mar', value: 13400 },
          { label: 'Apr', value: 14982 },
          { label: 'May', value: 20062 },
        ],
        tooltip: { index: 3, value: '$18,645.23' },
        yAxis: ['$25K', '$20K', '$15K', '$10K', '$5K', '$0'],
        xAxis: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
      },
    },
    openingBalance: '$14,982.23',
    totalCredits: '$37,842.19',
    totalDebits: '-$32,761.91',
    closingBalance: '$20,062.51',
  },
  payoutSchedule: [
    { date: 'May 15, 2025', relative: 'In 3 days', amount: '$12,450.00', status: 'Scheduled', tone: 'scheduled' },
    { date: 'May 29, 2025', relative: 'In 17 days', amount: '$11,200.00', status: 'Scheduled', tone: 'scheduled' },
    { date: 'Jun 12, 2025', relative: 'In 31 days', amount: '$10,800.00', status: 'Scheduled', tone: 'scheduled' },
  ],
  paymentMethods: [
    { id: 'visa-demo', brand: 'Visa', masked: '•••• 0000', expiry: 'Expires 05/27', primary: true, brandTone: 'visa' },
    { id: 'mastercard-demo', brand: 'Mastercard', masked: '•••• 1111', expiry: 'Expires 03/26', primary: false, brandTone: 'mastercard' },
    { id: 'bank-demo', brand: 'Bank transfer', masked: '•••• 2222', expiry: 'Checking account', primary: false, brandTone: 'bank' },
  ],
  recentPayouts: [
    { id: 'PAYOUT-DEMO-0415', date: 'Apr 30, 2025 09:12 AM', amount: '$12,450.00', method: 'Visa · •••• 0000', methodTone: 'visa', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-7X9L2' },
    { id: 'PAYOUT-DEMO-0331', date: 'Apr 15, 2025 09:08 AM', amount: '$11,680.00', method: 'Visa · •••• 0000', methodTone: 'visa', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-2J9P4' },
    { id: 'PAYOUT-DEMO-0317', date: 'Mar 31, 2025 09:04 AM', amount: '$10,950.00', method: 'Mastercard · •••• 1111', methodTone: 'mastercard', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-9M2D8' },
    { id: 'PAYOUT-DEMO-0303', date: 'Mar 17, 2025 09:01 AM', amount: '$10,320.00', method: 'Bank · •••• 2222', methodTone: 'bank', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-4J1H6' },
    { id: 'PAYOUT-DEMO-0217', date: 'Mar 03, 2025 08:59 AM', amount: '$9,870.00', method: 'Bank · •••• 2222', methodTone: 'bank', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-7P5Q1' },
  ],
};

export const transactionHistoryPageData = {
  demoOnly: true,
  totalCount: 1238,
  pageSize: 10,
  summary: [
    { id: 'total-sales', label: 'Total sales', value: '$126,431.28', note: '↑ 12.4% vs May 05 – May 12, 2025', tone: 'coral', noteTone: 'positive', icon: 'dollar' },
    { id: 'locked-commission', label: 'Locked commission', value: '$0.00', note: '— 0.0% vs May 05 – May 12, 2025', tone: 'green', noteTone: 'neutral', icon: 'shield' },
    { id: 'total-commission', label: 'Total commission', value: '$25,248.63', note: '↑ 8.7% vs May 05 – May 12, 2025', tone: 'coral', noteTone: 'positive', icon: 'coins' },
    { id: 'estimated-commission', label: 'Estimated commission', value: '$3,821.19', note: '↑ 5.3% vs May 05 – May 12, 2025', tone: 'orange', noteTone: 'positive', icon: 'chart' },
  ],
  filters: {
    timeRanges: [
      { value: 'last-7d', label: 'May 05 – May 12, 2025' },
      { value: 'last-30d', label: 'Apr 13 – May 12, 2025' },
      { value: 'year', label: 'Jan 01 – May 12, 2025' },
    ],
    orderStatuses: [
      { value: 'all', label: 'All order statuses' },
      { value: 'Paid', label: 'Paid' },
      { value: 'Pending', label: 'Pending' },
      { value: 'Void', label: 'Void' },
    ],
    skuStatuses: [
      { value: 'all', label: 'All SKU statuses' },
      { value: 'In stock', label: 'In stock' },
      { value: 'Backordered', label: 'Backordered' },
    ],
    transactionTypes: [
      { value: 'all', label: 'All transaction types' },
      { value: 'Sale', label: 'Sale' },
      { value: 'Refund', label: 'Refund' },
    ],
    groups: [
      { value: 'all', label: 'All groups' },
      { value: '182', label: 'Group 182' },
      { value: '181', label: 'Group 181' },
    ],
    publishers: [
      { value: 'all', label: 'All publishers' },
      { value: 'Demo Publisher A', label: 'Demo Publisher A' },
      { value: 'Demo Publisher B', label: 'Demo Publisher B' },
      { value: 'Demo Publisher C', label: 'Demo Publisher C' },
    ],
    channels: [
      { value: 'all', label: 'All channels' },
      { value: 'Instagram', label: 'Instagram' },
      { value: 'YouTube', label: 'YouTube' },
      { value: 'TikTok', label: 'TikTok' },
      { value: 'Blog', label: 'Blog' },
    ],
    commissionRules: [
      { value: 'all', label: 'All commission rules' },
      { value: 'Standard 9%', label: 'Standard 9%' },
      { value: 'Standard 10%', label: 'Standard 10%' },
      { value: 'Holiday 8%', label: 'Holiday 8%' },
    ],
    countries: [
      { value: 'all', label: 'All countries' },
      { value: 'United States', label: 'United States' },
      { value: 'Canada', label: 'Canada' },
      { value: 'United Kingdom', label: 'United Kingdom' },
      { value: 'Australia', label: 'Australia' },
      { value: 'Germany', label: 'Germany' },
      { value: 'France', label: 'France' },
      { value: 'Japan', label: 'Japan' },
      { value: 'Brazil', label: 'Brazil' },
      { value: 'Italy', label: 'Italy' },
    ],
    amazonBrands: [
      { value: 'all', label: 'All Amazon brands' },
      { value: 'Demo Brand', label: 'Demo Brand' },
      { value: 'Northstar Demo', label: 'Northstar Demo' },
      { value: 'PartnerBoost', label: 'PartnerBoost' },
    ],
  },
  rows: [
    { id: 'YP-250512-0001', date: 'May 12, 2025 14:32', datetime: '2025-05-12T14:32:00', itemCount: 1, items: [{ name: 'Demo Linen Shirt', sku: 'SKU-DEMO-1001', quantity: 1 }], quantity: 1, country: 'United States', amazonBrand: 'Demo Brand', salesAmount: '$129.99', commissionId: 'CM-250512-001', commission: '$11.70 (9%)', couponCode: 'WELCOME10', group: '182', status: 'Paid', statusTone: 'paid', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher A', channel: 'Instagram', commissionRule: 'Standard 9%' },
    { id: 'YP-250512-0002', date: 'May 12, 2025 13:18', datetime: '2025-05-12T13:18:00', itemCount: 2, items: [{ name: 'Demo Travel Tote', sku: 'SKU-DEMO-1002', quantity: 1 }, { name: 'Demo Cotton Cap', sku: 'SKU-DEMO-1003', quantity: 1 }], quantity: 2, country: 'Canada', amazonBrand: 'Northstar Demo', salesAmount: '$199.98', commissionId: 'CM-250512-002', commission: '$18.00 (9%)', couponCode: '—', group: '182', status: 'Paid', statusTone: 'paid', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher B', channel: 'YouTube', commissionRule: 'Standard 9%' },
    { id: 'YP-250512-0003', date: 'May 12, 2025 11:05', datetime: '2025-05-12T11:05:00', itemCount: 1, items: [{ name: 'Demo Everyday Sneaker', sku: 'SKU-DEMO-1004', quantity: 1 }], quantity: 1, country: 'United Kingdom', amazonBrand: 'PartnerBoost', salesAmount: '$89.00', commissionId: 'CM-250512-003', commission: '$8.90 (10%)', couponCode: 'SPRING20', group: '182', status: 'Paid', statusTone: 'paid', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher C', channel: 'TikTok', commissionRule: 'Standard 10%' },
    { id: 'YP-250512-0004', date: 'May 12, 2025 10:21', datetime: '2025-05-12T10:21:00', itemCount: 3, items: [{ name: 'Demo Canvas Pouch', sku: 'SKU-DEMO-1005', quantity: 1 }, { name: 'Demo Travel Tote', sku: 'SKU-DEMO-1002', quantity: 1 }, { name: 'Demo Cotton Cap', sku: 'SKU-DEMO-1003', quantity: 1 }], quantity: 3, country: 'Australia', amazonBrand: 'Demo Brand', salesAmount: '$149.97', commissionId: 'CM-250512-004', commission: '$13.50 (9%)', couponCode: '—', group: '182', status: 'Paid', statusTone: 'paid', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher A', channel: 'Blog', commissionRule: 'Standard 9%' },
    { id: 'YP-250512-0005', date: 'May 12, 2025 09:12', datetime: '2025-05-12T09:12:00', itemCount: 1, items: [{ name: 'Demo Weekend Jacket', sku: 'SKU-DEMO-1006', quantity: 1 }], quantity: 1, country: 'Germany', amazonBrand: 'Northstar Demo', salesAmount: '$79.99', commissionId: 'CM-250512-005', commission: '$6.40 (8%)', couponCode: '—', group: '182', status: 'Pending', statusTone: 'pending', skuStatus: 'Backordered', transactionType: 'Sale', publisher: 'Demo Publisher B', channel: 'Instagram', commissionRule: 'Holiday 8%' },
    { id: 'YP-250511-0999', date: 'May 11, 2025 22:47', datetime: '2025-05-11T22:47:00', itemCount: 2, items: [{ name: 'Demo Linen Shirt', sku: 'SKU-DEMO-1001', quantity: 1 }, { name: 'Demo Canvas Pouch', sku: 'SKU-DEMO-1005', quantity: 1 }], quantity: 1, country: 'France', amazonBrand: 'Demo Brand', salesAmount: '$59.99', commissionId: 'CM-250511-999', commission: '$5.40 (9%)', couponCode: 'SAVE15', group: '181', status: 'Paid', statusTone: 'paid', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher C', channel: 'YouTube', commissionRule: 'Standard 9%' },
    { id: 'YP-250511-0998', date: 'May 11, 2025 21:33', datetime: '2025-05-11T21:33:00', itemCount: 1, items: [{ name: 'Demo Utility Backpack', sku: 'SKU-DEMO-1007', quantity: 1 }], quantity: 1, country: 'Japan', amazonBrand: 'PartnerBoost', salesAmount: '$109.00', commissionId: 'CM-250511-998', commission: '$9.81 (9%)', couponCode: '—', group: '181', status: 'Paid', statusTone: 'paid', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher A', channel: 'Instagram', commissionRule: 'Standard 9%' },
    { id: 'YP-250511-0997', date: 'May 11, 2025 19:16', datetime: '2025-05-11T19:16:00', itemCount: 4, items: [{ name: 'Demo Travel Tote', sku: 'SKU-DEMO-1002', quantity: 2 }, { name: 'Demo Cotton Cap', sku: 'SKU-DEMO-1003', quantity: 2 }], quantity: 2, country: 'United States', amazonBrand: 'Demo Brand', salesAmount: '$239.80', commissionId: 'CM-250511-997', commission: '$21.58 (9%)', couponCode: 'WELCOME10', group: '181', status: 'Paid', statusTone: 'paid', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher B', channel: 'TikTok', commissionRule: 'Standard 9%' },
    { id: 'YP-250511-0996', date: 'May 11, 2025 17:02', datetime: '2025-05-11T17:02:00', itemCount: 1, items: [{ name: 'Demo Everyday Sneaker', sku: 'SKU-DEMO-1004', quantity: 1 }], quantity: 1, country: 'Brazil', amazonBrand: 'Northstar Demo', salesAmount: '$69.90', commissionId: 'CM-250511-996', commission: '$5.59 (8%)', couponCode: '—', group: '181', status: 'Void', statusTone: 'void', skuStatus: 'In stock', transactionType: 'Refund', publisher: 'Demo Publisher C', channel: 'Blog', commissionRule: 'Holiday 8%' },
    { id: 'YP-250511-0995', date: 'May 11, 2025 15:48', datetime: '2025-05-11T15:48:00', itemCount: 2, items: [{ name: 'Demo Canvas Pouch', sku: 'SKU-DEMO-1005', quantity: 1 }, { name: 'Demo Weekend Jacket', sku: 'SKU-DEMO-1006', quantity: 1 }], quantity: 1, country: 'Italy', amazonBrand: 'PartnerBoost', salesAmount: '$99.90', commissionId: 'CM-250511-995', commission: '$8.91 (9%)', couponCode: 'SUMMER25', group: '181', status: 'Paid', statusTone: 'paid', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher A', channel: 'YouTube', commissionRule: 'Standard 9%' },
    { id: 'YP-250510-0988', date: 'May 10, 2025 12:11', datetime: '2025-05-10T12:11:00', itemCount: 1, items: [{ name: 'Demo Utility Backpack', sku: 'SKU-DEMO-1007', quantity: 1 }], quantity: 1, country: 'United States', amazonBrand: 'Demo Brand', salesAmount: '$149.00', commissionId: 'CM-250510-988', commission: '$14.90 (10%)', couponCode: '—', group: '182', status: 'Pending', statusTone: 'pending', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher B', channel: 'TikTok', commissionRule: 'Standard 10%' },
    { id: 'YP-250509-0977', date: 'May 09, 2025 16:40', datetime: '2025-05-09T16:40:00', itemCount: 1, items: [{ name: 'Demo Everyday Sneaker', sku: 'SKU-DEMO-1004', quantity: 1 }], quantity: 1, country: 'Canada', amazonBrand: 'Northstar Demo', salesAmount: '$119.00', commissionId: 'CM-250509-977', commission: '$10.71 (9%)', couponCode: 'SPRING20', group: '182', status: 'Paid', statusTone: 'paid', skuStatus: 'In stock', transactionType: 'Sale', publisher: 'Demo Publisher C', channel: 'Instagram', commissionRule: 'Standard 9%' },
  ],
};

export const helpCenterPageData = {
  demoOnly: true,
  categories: [
    {
      id: 'getting-started',
      label: 'Getting started',
      description: 'New to the platform? Learn the basics and set up your account for success.',
      articles: 12,
      guides: 5,
      icon: 'rocket',
      tone: 'coral',
    },
    {
      id: 'partner-management',
      label: 'Partner management',
      description: 'Manage partners, review applications, and grow your affiliate network.',
      articles: 18,
      guides: 7,
      icon: 'users',
      tone: 'green',
    },
    {
      id: 'payments-reporting',
      label: 'Payments & reporting',
      description: 'Understand commissions, payouts, and performance reports.',
      articles: 14,
      guides: 6,
      icon: 'card',
      tone: 'purple',
    },
  ],
  articles: [
    {
      id: 'getting-started-with-yeahpromos',
      title: 'Getting started with YeahPromos',
      description: 'A step-by-step guide to set up your merchant account and launch your first program.',
      category: 'Getting started',
      updated: 'May 08, 2025',
      datetime: '2025-05-08',
    },
    {
      id: 'create-affiliate-program',
      title: 'How to create an affiliate program',
      description: 'Learn how to configure program settings, commission plans, and partner terms.',
      category: 'Getting started',
      updated: 'May 05, 2025',
      datetime: '2025-05-05',
    },
    {
      id: 'approve-partner-applications',
      title: 'Review and approve partner applications',
      description: 'How to review, approve, or decline applications from potential partners.',
      category: 'Partner management',
      updated: 'Apr 30, 2025',
      datetime: '2025-04-30',
    },
    {
      id: 'commissions-and-payouts',
      title: 'Understanding commissions and payouts',
      description: 'Learn how commissions are calculated, payouts are scheduled, and payment methods work.',
      category: 'Payments & reporting',
      updated: 'Apr 28, 2025',
      datetime: '2025-04-28',
    },
    {
      id: 'export-performance-reports',
      title: 'Generate and export performance reports',
      description: 'Create custom reports to track clicks, conversions, and earnings.',
      category: 'Payments & reporting',
      updated: 'Apr 26, 2025',
      datetime: '2025-04-26',
    },
    {
      id: 'invite-your-first-partner',
      title: 'Invite your first partner',
      description: 'Use partner discovery and invitations to build your first partner pipeline.',
      category: 'Partner management',
      updated: 'Apr 24, 2025',
      datetime: '2025-04-24',
    },
    {
      id: 'connect-your-store',
      title: 'Connect your store and verify tracking',
      description: 'Check your store connection, tracking provider, and first conversion signals.',
      category: 'Getting started',
      updated: 'Apr 22, 2025',
      datetime: '2025-04-22',
    },
    {
      id: 'read-performance-dashboard',
      title: 'Read your performance dashboard',
      description: 'Understand the metrics that explain partner activity, sales, and commission health.',
      category: 'Payments & reporting',
      updated: 'Apr 20, 2025',
      datetime: '2025-04-20',
    },
  ],
  systems: [
    { id: 'platform', label: 'Platform', status: 'Operational' },
    { id: 'partner-dashboard', label: 'Partner Dashboard', status: 'Operational' },
    { id: 'email-delivery', label: 'Email Delivery', status: 'Operational' },
    { id: 'payment-processing', label: 'Payment Processing', status: 'Operational' },
  ],
};

export const teamAccountsPageData = {
  demoOnly: true,
  summary: {
    activeMembers: 12,
    totalSeats: 20,
    pendingInvites: 3,
    availableSeats: 8,
  },
  filters: {
    brands: [
      { value: 'all', label: 'All brands' },
      { value: 'Brand A', label: 'Brand A' },
      { value: 'Brand B', label: 'Brand B' },
      { value: 'Brand C', label: 'Brand C' },
    ],
    roles: [
      { value: 'all', label: 'All roles' },
      { value: 'Admin', label: 'Admin' },
      { value: 'Manager', label: 'Manager' },
      { value: 'Editor', label: 'Editor' },
      { value: 'Analyst', label: 'Analyst' },
      { value: 'Viewer', label: 'Viewer' },
    ],
    statuses: [
      { value: 'all', label: 'All statuses' },
      { value: 'Active', label: 'Active' },
      { value: 'Pending', label: 'Pending' },
    ],
  },
  accounts: [
    { id: 'ethan-turner', initials: 'ET', avatarTone: 'purple', name: 'Ethan Turner', username: 'ethan.turner', role: 'Admin', scope: ['All Brands'], lastActive: 'May 12, 2025 09:41 AM', datetime: '2025-05-12T09:41:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'liam-smith', initials: 'LS', avatarTone: 'blue', name: 'Liam Smith', username: 'liam.smith', role: 'Manager', scope: ['Brand A', 'Brand B'], lastActive: 'May 12, 2025 08:15 AM', datetime: '2025-05-12T08:15:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'noah-ortiz', initials: 'NO', avatarTone: 'orange', name: 'Noah Ortiz', username: 'noah.ortiz', role: 'Editor', scope: ['Brand A'], lastActive: 'May 11, 2025 04:32 PM', datetime: '2025-05-11T16:32:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'ava-johnson', initials: 'AJ', avatarTone: 'red', name: 'Ava Johnson', username: 'ava.johnson', role: 'Analyst', scope: ['Brand B', 'Brand C'], lastActive: 'May 11, 2025 11:03 AM', datetime: '2025-05-11T11:03:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'mia-scott', initials: 'MS', avatarTone: 'green', name: 'Mia Scott', username: 'mia.scott', role: 'Viewer', scope: ['Brand C'], lastActive: 'May 10, 2025 03:28 PM', datetime: '2025-05-10T15:28:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'james-walker', initials: 'JW', avatarTone: 'yellow', name: 'James Walker', username: 'james.walker', role: 'Manager', scope: ['All Brands'], lastActive: 'May 10, 2025 09:11 AM', datetime: '2025-05-10T09:11:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'isabella-sanchez', initials: 'IS', avatarTone: 'purple', name: 'Isabella Sanchez', username: 'isabella.sanchez', role: 'Editor', scope: ['Brand A', 'Brand B'], lastActive: 'May 09, 2025 02:45 PM', datetime: '2025-05-09T14:45:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'benjamin-davis', initials: 'BD', avatarTone: 'blue', name: 'Benjamin Davis', username: 'benjamin.davis', role: 'Viewer', scope: ['Brand B'], lastActive: 'May 08, 2025 10:22 AM', datetime: '2025-05-08T10:22:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'olivia-lee', initials: 'OL', avatarTone: 'orange', name: 'Olivia Lee', username: 'olivia.lee', role: 'Editor', scope: ['Brand C'], lastActive: 'May 07, 2025 05:18 PM', datetime: '2025-05-07T17:18:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'william-martinez', initials: 'WM', avatarTone: 'cyan', name: 'William Martinez', username: 'william.martinez', role: 'Analyst', scope: ['Brand A', 'Brand C'], lastActive: 'May 07, 2025 09:07 AM', datetime: '2025-05-07T09:07:00', status: 'Pending', statusTone: 'pending', mfa: 'Not enrolled' },
    { id: 'caroline-white', initials: 'CW', avatarTone: 'pink', name: 'Caroline White', username: 'caroline.white', role: 'Analyst', scope: ['Brand A'], lastActive: 'May 06, 2025 01:26 PM', datetime: '2025-05-06T13:26:00', status: 'Pending', statusTone: 'pending', mfa: 'Not enrolled' },
    { id: 'daniel-kim', initials: 'DK', avatarTone: 'green', name: 'Daniel Kim', username: 'daniel.kim', role: 'Viewer', scope: ['Brand B'], lastActive: 'May 05, 2025 10:48 AM', datetime: '2025-05-05T10:48:00', status: 'Pending', statusTone: 'pending', mfa: 'Not enrolled' },
    { id: 'sophia-morgan', initials: 'SM', avatarTone: 'purple', name: 'Sophia Morgan', username: 'sophia.morgan', role: 'Manager', scope: ['Brand A', 'Brand C'], lastActive: 'May 04, 2025 03:12 PM', datetime: '2025-05-04T15:12:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'lucas-brown', initials: 'LB', avatarTone: 'blue', name: 'Lucas Brown', username: 'lucas.brown', role: 'Editor', scope: ['Brand B'], lastActive: 'May 03, 2025 11:39 AM', datetime: '2025-05-03T11:39:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
    { id: 'grace-wilson', initials: 'GW', avatarTone: 'red', name: 'Grace Wilson', username: 'grace.wilson', role: 'Viewer', scope: ['Brand C'], lastActive: 'May 02, 2025 09:18 AM', datetime: '2025-05-02T09:18:00', status: 'Active', statusTone: 'active', mfa: 'Enabled' },
  ],
  totalCount: 15,
  pageSize: 10,
};

export const recruitmentPageSettingsData = {
  demoOnly: true,
  status: 'published',
  brands: [
    { value: 'demo-brand', label: 'Demo Brand' },
    { value: 'partner-boost', label: 'PartnerBoost' },
    { value: 'northstar-demo', label: 'Northstar Demo' },
  ],
  queues: [
    { value: 'new', label: 'New applications' },
    { value: 'under-review', label: 'Under review' },
    { value: 'custom', label: 'Custom review queue' },
  ],
  publicUrl: 'partners.yeahpromos.com/demo-brand',
  title: 'Partner with Demo Brand',
  description: 'Share products you love, reach new customers, and grow with a partner program built for you.',
  cta: 'Apply to partner',
  applicationFields: [
    { id: 'full-name', label: 'Full name', detail: 'Required', required: true, enabled: true, icon: 'users' },
    { id: 'email', label: 'Email address', detail: 'Required', required: true, enabled: true, icon: 'message' },
    { id: 'website', label: 'Website or profile URL', detail: 'Optional', required: false, enabled: true, icon: 'globe' },
    { id: 'platform', label: 'Primary platform', detail: 'Optional', required: false, enabled: true, icon: 'grid' },
    { id: 'audience-size', label: 'Audience size', detail: 'Optional', required: false, enabled: false, icon: 'chart' },
    { id: 'partner-note', label: 'Why do you want to partner?', detail: 'Optional', required: false, enabled: false, icon: 'edit' },
  ],
  checklist: [
    { label: 'Brand connected', detail: 'Demo Store is active', tone: 'success' },
    { label: 'Application queue selected', detail: 'New applications', tone: 'success' },
    { label: 'Public link available', detail: 'Ready to share with partners', tone: 'success' },
  ],
};
export const brandIntegrationPageData = {
  demoOnly: true,
  brand: {
    name: 'Demo Store',
    status: 'Active',
    domain: 'demo-store.com',
    timezone: '(GMT-04:00) New York, US',
    currency: 'USD – US Dollar',
    owner: 'Demo1 Admin',
    billingPlan: 'Growth Plan',
  },
  health: {
    percentage: 96,
    window: 'Last 24 hours',
    counts: [
      { label: 'Healthy', value: 4, tone: 'healthy' },
      { label: 'Warning', value: 0, tone: 'warning' },
      { label: 'Error', value: 0, tone: 'error' },
    ],
  },
  integrations: [
    {
      id: 'shopify-storefront',
      name: 'Storefront (Shopify)',
      icon: 'bag',
      iconTone: 'shopify',
      status: 'Connected',
      statusTone: 'connected',
      lastSync: 'May 12, 2025 09:30 AM',
      scope: ['Products', 'Orders', 'Customers', 'Inventory'],
      dataStatus: [
        { label: 'Products', value: '2,842 products' },
        { label: 'Orders', value: '1,256 orders' },
        { label: 'Customers', value: '4,523 customers' },
        { label: 'Inventory', value: '98% in stock' },
      ],
      action: 'Manage',
      actionTone: 'manage',
    },
    {
      id: 'woocommerce-store',
      name: 'Online Store (WooCommerce)',
      icon: 'cart',
      iconTone: 'woocommerce',
      status: 'Connected',
      statusTone: 'connected',
      lastSync: 'May 12, 2025 09:12 AM',
      scope: ['Products', 'Orders', 'Customers'],
      dataStatus: [
        { label: 'Products', value: '1,115 products' },
        { label: 'Orders', value: '732 orders' },
        { label: 'Customers', value: '1,985 customers' },
      ],
      action: 'Manage',
      actionTone: 'manage',
    },
    {
      id: 'amazon-marketplace',
      name: 'Marketplace (Amazon)',
      icon: 'amazon',
      iconTone: 'amazon',
      status: 'Warning',
      statusTone: 'warning',
      lastSync: 'May 12, 2025 07:45 AM',
      scope: ['Products', 'Orders'],
      dataStatus: [
        { label: 'Products', value: '432 products' },
        { label: 'Orders', value: 'Sync delayed' },
      ],
      action: 'Reconnect',
      actionTone: 'reconnect',
    },
    {
      id: 'web-analytics',
      name: 'Web Analytics',
      icon: 'chart',
      iconTone: 'analytics',
      status: 'Connected',
      statusTone: 'connected',
      lastSync: 'May 12, 2025 09:28 AM',
      scope: ['Traffic', 'Conversions', 'Campaigns'],
      dataStatus: [
        { label: 'Traffic', value: '98% events received' },
        { label: 'Conversions', value: '1,842 conversions' },
        { label: 'Campaigns', value: '12 campaigns' },
      ],
      action: 'Manage',
      actionTone: 'manage',
    },
  ],
  recentActivity: [
    {
      id: 'shopify-sync',
      icon: 'bag',
      iconTone: 'shopify',
      tone: 'connected',
      title: 'Shopify sync completed successfully',
      detail: '2,842 products synced',
      time: 'May 12, 2025 09:30 AM',
    },
    {
      id: 'woocommerce-sync',
      icon: 'cart',
      iconTone: 'woocommerce',
      tone: 'connected',
      title: 'WooCommerce sync completed',
      detail: '1,115 products synced',
      time: 'May 12, 2025 09:12 AM',
    },
    {
      id: 'amazon-sync',
      icon: 'amazon',
      iconTone: 'amazon',
      tone: 'warning',
      title: 'Amazon sync delayed',
      detail: 'Retrying in 30 minutes',
      time: 'May 12, 2025 07:45 AM',
    },
    {
      id: 'analytics-update',
      icon: 'chart',
      iconTone: 'analytics',
      tone: 'connected',
      title: 'Analytics data updated',
      detail: '1,842 conversions tracked',
      time: 'May 12, 2025 09:28 AM',
    },
    {
      id: 'settings-update',
      icon: 'bag',
      iconTone: 'shopify',
      tone: 'connected',
      title: 'Integration settings updated',
      detail: 'Shopify data scope changed',
      time: 'May 11, 2025 04:15 PM',
    },
  ],
};

export const apiCredentialsPageData = {
  demoOnly: true,
  credentials: [
    {
      id: 'reporting-service',
      environment: 'live',
      name: 'Reporting Service Key',
      masked: '••••••••••••8d3f',
      createdBy: { initials: 'RA', name: 'Riley Anderson', detail: 'riley.anderson · demo account' },
      createdOn: 'May 12, 2025',
      createdTime: '10:24 AM',
      lastUsed: 'May 12, 2025',
      lastUsedTime: '10:24 AM',
      scopes: ['Reports', 'Performance'],
      extraScopes: 2,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'automation-worker',
      environment: 'live',
      name: 'Automation Worker',
      masked: '••••••••••••b7a2',
      createdBy: { initials: 'JS', name: 'Jamie Santos', detail: 'jamie.santos · demo account' },
      createdOn: 'May 08, 2025',
      createdTime: '03:15 PM',
      lastUsed: 'May 11, 2025',
      lastUsedTime: '11:47 PM',
      scopes: ['Transactions', 'Campaigns'],
      extraScopes: 1,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'finance-integration',
      environment: 'live',
      name: 'Finance Integration',
      masked: '••••••••••••f91c',
      createdBy: { initials: 'MW', name: 'Morgan White', detail: 'morgan.white · demo account' },
      createdOn: 'Apr 29, 2025',
      createdTime: '09:02 AM',
      lastUsed: 'May 10, 2025',
      lastUsedTime: '08:33 AM',
      scopes: ['Transactions', 'Payouts'],
      extraScopes: 0,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'data-exporter',
      environment: 'live',
      name: 'Data Exporter',
      masked: '••••••••••••3c19',
      createdBy: { initials: 'DL', name: 'Drew Lee', detail: 'drew.lee · demo account' },
      createdOn: 'Apr 21, 2025',
      createdTime: '02:41 PM',
      lastUsed: 'May 09, 2025',
      lastUsedTime: '01:12 PM',
      scopes: ['Reports', 'Data Export'],
      extraScopes: 0,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'legacy-app-access',
      environment: 'live',
      name: 'Legacy App Access',
      masked: '••••••••••••9e14',
      createdBy: { initials: 'SA', name: 'Sam Adams', detail: 'sam.adams · demo account' },
      createdOn: 'Mar 18, 2025',
      createdTime: '05:36 PM',
      lastUsed: 'Apr 25, 2025',
      lastUsedTime: '04:21 PM',
      scopes: ['Reports', 'Performance'],
      extraScopes: 0,
      status: 'Inactive',
      statusTone: 'inactive',
    },
    {
      id: 'sandbox-testing',
      environment: 'live',
      name: 'Sandbox Testing Key',
      masked: '••••••••••••d5f7',
      createdBy: { initials: 'TC', name: 'Taylor Chen', detail: 'taylor.chen · demo account' },
      createdOn: 'Feb 10, 2025',
      createdTime: '11:18 AM',
      lastUsed: 'Never',
      lastUsedTime: '',
      scopes: ['Test Data'],
      extraScopes: 0,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'test-reporting',
      environment: 'test',
      name: 'Test Reporting Key',
      masked: '••••••••••••1a42',
      createdBy: { initials: 'RA', name: 'Riley Anderson', detail: 'riley.anderson · demo account' },
      createdOn: 'May 02, 2025',
      createdTime: '09:18 AM',
      lastUsed: 'May 12, 2025',
      lastUsedTime: '09:46 AM',
      scopes: ['Reports', 'Test Data'],
      extraScopes: 1,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'test-automation',
      environment: 'test',
      name: 'Test Automation Worker',
      masked: '••••••••••••6e08',
      createdBy: { initials: 'JS', name: 'Jamie Santos', detail: 'jamie.santos · demo account' },
      createdOn: 'Apr 26, 2025',
      createdTime: '02:05 PM',
      lastUsed: 'May 07, 2025',
      lastUsedTime: '04:11 PM',
      scopes: ['Transactions', 'Test Data'],
      extraScopes: 0,
      status: 'Inactive',
      statusTone: 'inactive',
    },
  ],
  webhooks: [
    {
      id: 'order-events',
      label: 'Order Events',
      status: 'Active',
      statusTone: 'active',
      url: 'https://••••••••••••••••••••••••.com/webhook/order',
    },
    {
      id: 'payout-events',
      label: 'Payout Events',
      status: 'Active',
      statusTone: 'active',
      url: 'https://••••••••••••••••••••••••.com/webhook/payout',
    },
    {
      id: 'partner-events',
      label: 'Partner Events',
      status: 'Active',
      statusTone: 'active',
      url: 'https://••••••••••••••••••••••••.com/webhook/partner',
    },
    {
      id: 'campaign-events',
      label: 'Campaign Events',
      status: 'Inactive',
      statusTone: 'inactive',
      url: 'https://••••••••••••••••••••••••.com/webhook/campaign',
    },
  ],
};

export const commissionInvoicesPageData = {
  demoOnly: true,
  totalCount: 73,
  dateRanges: [
    { id: 'last-7d', label: 'May 05 – May 12, 2025' },
    { id: 'last-30d', label: 'Apr 13 – May 12, 2025' },
    { id: 'last-90d', label: 'Feb 12 – May 12, 2025' },
  ],
  filters: {
    paymentMethod: [
      { value: 'all', label: 'All methods' },
      { value: 'Account credits', label: 'Account credits' },
      { value: 'Credit card', label: 'Credit card' },
      { value: 'Bank transfer', label: 'Bank transfer' },
    ],
    paymentType: [
      { value: 'all', label: 'All types' },
      { value: 'Publisher payout', label: 'Publisher payout' },
      { value: 'Price plan fee', label: 'Price plan fee' },
      { value: 'Account deposit', label: 'Account deposit' },
    ],
    status: [
      { value: 'all', label: 'All statuses' },
      { value: 'Paid', label: 'Paid' },
      { value: 'Pending', label: 'Pending' },
      { value: 'Failed', label: 'Failed' },
    ],
    brand: [
      { value: 'all', label: 'All brands' },
      { value: 'PartnerBoost', label: 'PartnerBoost' },
      { value: 'PartnerMatic', label: 'PartnerMatic' },
      { value: 'Northstar Demo', label: 'Northstar Demo' },
    ],
  },
  rows: [
    { id: 'INV-250512-0712', date: 'May 12, 2025 14:32', brand: 'PartnerBoost', paymentMethod: 'Account credits', paymentType: 'Publisher payout', description: 'Auto charged commission balance', amount: '-$0.00', status: 'Paid', statusTone: 'paid' },
    { id: 'INV-250511-0611', date: 'May 11, 2025 22:18', brand: 'PartnerMatic', paymentMethod: 'Account credits', paymentType: 'Price plan fee', description: 'Fees for Standard Plan', amount: '-$50.00', status: 'Paid', statusTone: 'paid' },
    { id: 'INV-250510-0438', date: 'May 10, 2025 21:06', brand: 'PartnerMatic', paymentMethod: 'Account credits', paymentType: 'Price plan fee', description: 'Fees for Standard Plan', amount: '-$50.00', status: 'Paid', statusTone: 'paid' },
    { id: 'INV-250510-0437', date: 'May 10, 2025 21:06', brand: 'PartnerBoost', paymentMethod: 'Credit card', paymentType: 'Account deposit', description: 'Account balance top-up', amount: '$500.00', status: 'Paid', statusTone: 'paid' },
    { id: 'INV-250509-0315', date: 'May 09, 2025 18:42', brand: 'Northstar Demo', paymentMethod: 'Bank transfer', paymentType: 'Publisher payout', description: 'Bi-weekly partner payout', amount: '-$320.00', status: 'Pending', statusTone: 'pending' },
  ],
};

export const couponsPageData = {
  demoOnly: true,
  totalCount: 6,
  dateRangeLabel: 'May 05, 2025  ~  May 12, 2025',
  tabs: [
    { id: 'banners-images', label: 'Banners & images' },
    { id: 'texts-emails', label: 'Texts & emails' },
    { id: 'coupons', label: 'Coupons' },
  ],
  filters: {
    statuses: [
      { value: 'all', label: 'All' },
      { value: 'Active', label: 'Active' },
      { value: 'Scheduled', label: 'Scheduled' },
      { value: 'Expired', label: 'Expired' },
    ],
    permissions: [
      { value: 'all', label: 'All' },
      { value: 'All partners', label: 'All partners' },
      { value: 'Technology partners', label: 'Technology partners' },
      { value: 'App users', label: 'App users' },
      { value: 'VIP partners', label: 'VIP partners' },
    ],
    categories: [
      { value: 'all', label: 'All categories' },
      { value: 'Sitewide', label: 'Sitewide' },
      { value: 'Electronics', label: 'Electronics' },
      { value: 'App Exclusive', label: 'App Exclusive' },
      { value: 'Clearance', label: 'Clearance' },
    ],
  },
  coupons: [
    {
      id: 'summer20',
      code: 'SUMMER20',
      offer: '20% off sitewide',
      requirement: 'Minimum spend $50',
      category: 'Sitewide',
      validFrom: 'May 01, 2025',
      validTo: 'May 31, 2025',
      usage: 324,
      usageLimit: 1000,
      permission: 'All partners',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'welcome10',
      code: 'WELCOME10',
      offer: '10% off for new customers',
      requirement: 'No minimum spend',
      category: 'Sitewide',
      validFrom: 'Apr 15, 2025',
      validTo: 'Jun 15, 2025',
      usage: 187,
      usageLimit: 500,
      permission: 'All partners',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'tech15',
      code: 'TECH15',
      offer: '15% off electronics',
      requirement: 'Minimum spend $100',
      category: 'Electronics',
      validFrom: 'Apr 20, 2025',
      validTo: 'May 20, 2025',
      usage: 93,
      usageLimit: 300,
      permission: 'Technology partners',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'appdownload5',
      code: 'APPDOWNLOAD5',
      offer: '$5 off on app orders',
      requirement: 'Minimum spend $30',
      category: 'App Exclusive',
      validFrom: 'Apr 01, 2025',
      validTo: 'Jun 30, 2025',
      usage: 256,
      usageLimit: 800,
      permission: 'App users',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'clearance25',
      code: 'CLEARANCE25',
      offer: '25% off clearance items',
      requirement: 'No minimum spend',
      category: 'Clearance',
      validFrom: 'Apr 10, 2025',
      validTo: 'Apr 30, 2025',
      usage: 410,
      usageLimit: 600,
      permission: 'All partners',
      status: 'Expired',
      statusTone: 'expired',
    },
    {
      id: 'vip30',
      code: 'VIP30',
      offer: '30% off for VIP members',
      requirement: 'Minimum spend $150',
      category: 'Sitewide',
      validFrom: 'May 10, 2025',
      validTo: 'Jun 10, 2025',
      usage: 68,
      usageLimit: 200,
      permission: 'VIP partners',
      status: 'Scheduled',
      statusTone: 'scheduled',
    },
  ],
};

export const bannersImagesPageData = {
  demoOnly: true,
  totalCount: 48,
  pageLabel: '1 – 12 of 48 assets',
  tabs: [
    { id: 'all-assets', label: 'All assets' },
    { id: 'banners', label: 'Banners' },
    { id: 'images', label: 'Images' },
    { id: 'logos', label: 'Logos' },
    { id: 'icons', label: 'Icons' },
    { id: 'gifs', label: 'GIFs' },
  ],
  filters: {
    folders: [
      { value: 'all', label: 'All folders' },
      { value: 'spring-sale', label: 'Spring Sale 2025' },
      { value: 'tech-essentials', label: 'Tech Essentials' },
      { value: 'beauty-picks', label: 'Beauty Picks' },
      { value: 'home-refresh', label: 'Home Refresh' },
      { value: 'affiliate-program', label: 'Affiliate Program' },
      { value: 'sitewide-promo', label: 'Sitewide Promo' },
    ],
    campaigns: [
      { value: 'all', label: 'All campaigns' },
      { value: 'spring-sale', label: 'Spring Sale 2025' },
      { value: 'tech-essentials', label: 'Tech Essentials' },
      { value: 'beauty-picks', label: 'Beauty Picks' },
      { value: 'home-refresh', label: 'Home Refresh' },
      { value: 'summer-collection', label: 'Summer Collection' },
    ],
    statuses: [
      { value: 'all', label: 'All statuses' },
      { value: 'Active', label: 'Active' },
      { value: 'In use', label: 'In use' },
      { value: 'Draft', label: 'Draft' },
    ],
  },
  assets: [
    {
      id: 'workspace-sale',
      category: 'banners',
      fileName: 'workspace-sale-1200x628.jpg',
      title: 'Elevate Your Workspace',
      subtitle: 'Up to 40% off select items',
      cta: 'Shop Now',
      dimensions: '1200 × 628',
      type: 'Image (JPG)',
      fileSize: '210 KB',
      uploaded: 'May 12, 2025 10:30 AM',
      uploadedBy: 'Demo1 Admin',
      folder: 'Spring Sale 2025',
      folderValue: 'spring-sale',
      campaign: 'Spring Sale 2025',
      campaignValue: 'spring-sale',
      usedIn: '3 campaigns',
      tags: ['sale', 'furniture', 'workspace', '+2'],
      description: 'Promotional banner for the Spring Sale campaign highlighting workspace furniture discount.',
      status: 'Active',
      statusTone: 'active',
      tone: 'workspace',
    },
    {
      id: 'audio-headphones',
      category: 'banners',
      fileName: 'audio-headphones-1200x628.jpg',
      title: 'Premium Sound Everyday',
      subtitle: 'Clear audio. All day long.',
      cta: 'Shop Now',
      dimensions: '1200 × 628',
      type: 'Image (JPG)',
      fileSize: '184 KB',
      uploaded: 'May 11, 2025 09:18 AM',
      uploadedBy: 'Demo1 Admin',
      folder: 'Tech Essentials',
      folderValue: 'tech-essentials',
      campaign: 'Tech Essentials',
      campaignValue: 'tech-essentials',
      usedIn: '2 campaigns',
      tags: ['audio', 'tech', 'summer', '+1'],
      description: 'Product banner for the Tech Essentials campaign featuring premium audio accessories.',
      status: 'In use',
      statusTone: 'in-use',
      tone: 'headphones',
    },
    {
      id: 'beauty-skincare',
      category: 'banners',
      fileName: 'beauty-skincare-1200x628.jpg',
      title: 'Clean Beauty Naturally',
      subtitle: 'Skincare that cares',
      cta: 'Shop Now',
      dimensions: '1200 × 628',
      type: 'Image (JPG)',
      fileSize: '196 KB',
      uploaded: 'May 10, 2025 16:42 PM',
      uploadedBy: 'Demo1 Admin',
      folder: 'Beauty Picks',
      folderValue: 'beauty-picks',
      campaign: 'Beauty Picks',
      campaignValue: 'beauty-picks',
      usedIn: '2 campaigns',
      tags: ['beauty', 'skincare', 'clean'],
      description: 'Clean beauty campaign creative with product-led messaging for partner promotion.',
      status: 'Active',
      statusTone: 'active',
      tone: 'beauty',
    },
    {
      id: 'home-furniture',
      category: 'banners',
      fileName: 'home-furniture-1200x628.jpg',
      title: 'Modern Design Made Simple',
      subtitle: 'Timeless pieces for every home',
      cta: 'Shop Now',
      dimensions: '1200 × 628',
      type: 'Image (JPG)',
      fileSize: '202 KB',
      uploaded: 'May 09, 2025 11:20 AM',
      uploadedBy: 'Demo1 Admin',
      folder: 'Home Refresh',
      folderValue: 'home-refresh',
      campaign: 'Home Refresh',
      campaignValue: 'home-refresh',
      usedIn: '1 campaign',
      tags: ['home', 'furniture', 'design'],
      description: 'Furniture creative prepared for the Home Refresh partner campaign.',
      status: 'Active',
      statusTone: 'active',
      tone: 'chair',
    },
    {
      id: 'running-shoes',
      category: 'banners',
      fileName: 'running-shoes-1200x628.jpg',
      title: 'Built for Performance',
      subtitle: 'Move faster. Go farther.',
      cta: 'Shop Now',
      dimensions: '1200 × 628',
      type: 'Image (JPG)',
      fileSize: '176 KB',
      uploaded: 'May 08, 2025 13:14 PM',
      uploadedBy: 'Demo1 Admin',
      folder: 'Active Lifestyle',
      folderValue: 'all',
      campaign: 'Summer Collection',
      campaignValue: 'summer-collection',
      usedIn: '2 campaigns',
      tags: ['running', 'sport', 'performance'],
      description: 'Performance footwear banner for the active lifestyle partner collection.',
      status: 'In use',
      statusTone: 'in-use',
      tone: 'shoes',
    },
    {
      id: 'summer-essentials',
      category: 'banners',
      fileName: 'summer-essentials-1200x628.jpg',
      title: 'Summer Essentials Up to 30% Off',
      subtitle: 'Limited time only',
      cta: 'Shop Now',
      dimensions: '1200 × 628',
      type: 'Image (JPG)',
      fileSize: '228 KB',
      uploaded: 'May 07, 2025 08:54 AM',
      uploadedBy: 'Demo1 Admin',
      folder: 'Summer Collection',
      folderValue: 'all',
      campaign: 'Summer Collection',
      campaignValue: 'summer-collection',
      usedIn: '0 campaigns',
      tags: ['summer', 'sale', 'accessories'],
      description: 'Draft seasonal banner for the next Summer Collection partner campaign.',
      status: 'Draft',
      statusTone: 'draft',
      tone: 'summer',
    },
    {
      id: 'affiliate-program',
      category: 'images',
      fileName: 'affiliate-program-728x90.jpg',
      title: 'Join Our Affiliate Program',
      subtitle: 'Earn more with every referral.',
      cta: 'Learn More',
      dimensions: '728 × 90',
      type: 'Image (JPG)',
      fileSize: '86 KB',
      uploaded: 'May 06, 2025 15:05 PM',
      uploadedBy: 'Demo1 Admin',
      folder: 'Affiliate Program',
      folderValue: 'affiliate-program',
      campaign: 'All campaigns',
      campaignValue: 'all',
      usedIn: '4 campaigns',
      tags: ['affiliate', 'recruiting', 'referral'],
      description: 'Sitewide recruitment banner inviting new partners to join the affiliate program.',
      status: 'Active',
      statusTone: 'active',
      tone: 'affiliate',
      strip: true,
    },
    {
      id: 'free-shipping',
      category: 'images',
      fileName: 'free-shipping-728x90.jpg',
      title: 'Free Shipping on Orders $50+',
      subtitle: 'Shop now and enjoy free standard shipping.',
      cta: '',
      dimensions: '728 × 90',
      type: 'Image (JPG)',
      fileSize: '74 KB',
      uploaded: 'May 05, 2025 10:15 AM',
      uploadedBy: 'Demo1 Admin',
      folder: 'Sitewide Promo',
      folderValue: 'sitewide-promo',
      campaign: 'All campaigns',
      campaignValue: 'all',
      usedIn: '5 campaigns',
      tags: ['shipping', 'promo', 'sitewide'],
      description: 'Sitewide shipping promotion for partners to use across active campaigns.',
      status: 'Active',
      statusTone: 'active',
      tone: 'shipping',
      strip: true,
    },
    {
      id: 'new-arrivals',
      category: 'images',
      fileName: 'new-arrivals-728x90.jpg',
      title: 'New Arrivals',
      subtitle: 'Discover what’s new this week.',
      cta: '',
      dimensions: '728 × 90',
      type: 'Image (JPG)',
      fileSize: '91 KB',
      uploaded: 'May 04, 2025 12:42 PM',
      uploadedBy: 'Demo1 Admin',
      folder: 'New Arrivals',
      folderValue: 'all',
      campaign: 'All campaigns',
      campaignValue: 'all',
      usedIn: '2 campaigns',
      tags: ['new', 'arrivals', 'lifestyle'],
      description: 'New arrival banner for partner placements and campaign landing pages.',
      status: 'In use',
      statusTone: 'in-use',
      tone: 'arrivals',
      strip: true,
    },
  ],
};

export const messagesPageData = {
  demoOnly: true,
  unreadCount: 8,
  tabs: [
    { id: 'all-messages', label: 'All Messages', count: 8 },
    { id: 'partner-messages', label: 'Partner Messages', count: 5 },
    { id: 'system-alerts', label: 'System Alerts', count: 2 },
    { id: 'archived-messages', label: 'Archived', count: null },
  ],
  filterOptions: [
    { value: 'all', label: 'All messages' },
    { value: 'unread', label: 'Unread only' },
    { value: 'partner', label: 'Partner messages' },
    { value: 'system', label: 'System alerts' },
  ],
  messages: [
    {
      id: 'message-alpha-media',
      sender: 'Alpha Media',
      initials: 'AM',
      avatarTone: 'rose',
      subject: 'Product collaboration proposal',
      preview: 'Hi Demo1 team, I’d love to discuss...',
      time: '10:24 AM',
      date: 'May 12, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: true,
    },
    {
      id: 'message-creative-bytes',
      sender: 'Creative Bytes',
      initials: 'CB',
      avatarTone: 'lavender',
      subject: 'Campaign content approval',
      preview: 'I’ve submitted the content for your...',
      time: '9:15 AM',
      date: 'May 12, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: true,
    },
    {
      id: 'message-future-hub',
      sender: 'Future Hub',
      initials: 'FH',
      avatarTone: 'blue',
      subject: 'Commission inquiry',
      preview: 'Could you confirm the commission...',
      time: 'Yesterday',
      date: 'May 11, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: false,
    },
    {
      id: 'message-system-payout',
      sender: 'System Alerts',
      initials: '!',
      avatarTone: 'alert',
      subject: 'Payout processed',
      preview: 'A payout of $2,431.25 has been...',
      time: 'Yesterday',
      date: 'May 11, 2025',
      category: 'system',
      kind: 'System Alert',
      unread: true,
    },
    {
      id: 'message-karma-collective',
      sender: 'Karma Collective',
      initials: 'KC',
      avatarTone: 'cyan',
      subject: 'Discount code request',
      preview: 'Hi, can we get a unique discount code...',
      time: 'May 11',
      date: 'May 11, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: false,
    },
    {
      id: 'message-partnerboost',
      sender: 'PartnerBoost Team',
      initials: 'PT',
      avatarTone: 'pink',
      subject: 'New feature: Campaign Auto-Invite',
      preview: 'We’re excited to announce a new...',
      time: 'May 10',
      date: 'May 10, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: false,
    },
    {
      id: 'message-gocertify',
      sender: 'GoCertify',
      initials: 'G',
      avatarTone: 'peach',
      subject: 'Performance update',
      preview: 'Here’s your performance for Apr 28 – May 4...',
      time: 'May 09',
      date: 'May 09, 2025',
      category: 'system',
      kind: 'System Alert',
      unread: false,
    },
    {
      id: 'message-influencer-success',
      sender: 'Influencer Success',
      initials: 'IS',
      avatarTone: 'mint',
      subject: 'Welcome to YeahPromos!',
      preview: 'Welcome aboard! We’re here to help...',
      time: 'May 08',
      date: 'May 08, 2025',
      category: 'archived',
      kind: 'Partner Message',
      unread: false,
    },
  ],
  conversation: {
    messageId: 'message-alpha-media',
    subject: 'Product collaboration proposal',
    kind: 'Partner Message',
    sender: {
      name: 'Alpha Media',
      initials: 'AM',
      avatarTone: 'rose',
      email: 'support [at] alphamedia.example',
    },
    recipient: {
      name: 'Demo1',
      initials: 'D1',
      avatarTone: 'slate',
      email: 'brand [at] demo1.example',
    },
    sent: 'May 12, 2025 10:24 AM',
    body: [
      'Hi Demo1 team,',
      'I’d love to discuss a potential product collaboration for our upcoming summer campaign. Our audience aligns closely with your brand, and I believe this could be a great opportunity for both of us.',
      'Please let me know if you’re open to a quick call this week.',
      'Looking forward to your response!',
      'Best regards,',
      'Alpha Media Team',
    ],
    attachments: [
      { name: 'Collaboration_Proposal.pdf', type: 'PDF', size: '1.2 MB', icon: 'file', tone: 'pdf' },
      { name: 'Audience_Insights.xlsx', type: 'XLSX', size: '854 KB', icon: 'chart', tone: 'sheet' },
      { name: 'Campaign_Moodboard.png', type: 'PNG', size: '2.4 MB', icon: 'file', tone: 'image' },
    ],
    replies: [
      { id: 'reply-demo1', sender: 'Demo1 (You)', initials: 'D1', avatarTone: 'slate', time: 'May 12, 2025 11:02 AM', body: 'Hi Alpha Media, thanks for reaching out! We’d be happy to explore this opportunity.\nAre you available for a call on Wednesday at 2 PM EST?' },
      { id: 'reply-alpha', sender: 'Alpha Media', initials: 'AM', avatarTone: 'rose', time: 'May 12, 2025 11:15 AM', body: 'Wednesday at 2 PM works great! I’ll send over a calendar invite.' },
    ],
  },
  partnerDetails: {
    name: 'Alpha Media',
    initials: 'AM',
    avatarTone: 'rose',
    location: 'United States',
    contact: 'contact [at] alphamedia.example',
    activeCampaigns: [
      { name: 'Summer Essentials 2025', dates: 'May 01 – May 31, 2025', status: 'Active' },
      { name: 'New Arrivals Launch', dates: 'Apr 15 – May 15, 2025', status: 'Active' },
    ],
    stats: [
      { label: 'Total Sales', value: '$24,812.45' },
      { label: 'Conversions', value: '1,246' },
      { label: 'Commission Earned', value: '$2,481.25' },
      { label: 'Pending Payout', value: '$1,120.00' },
    ],
    conversationId: 'MSG-20250512-1024',
    conversationStatus: 'Open',
    labels: '+',
    addedToCrm: 'Yes',
  },
};
