const sevenDaySnapshot = {
  metrics: [
    { id: 'clicks', label: 'Clicks', value: '48,620', change: '+12.8%', note: 'vs previous period', tone: 'blue', icon: 'cursor' },
    { id: 'orders', label: 'Orders', value: '1,284', change: '+8.4%', note: 'completed orders', tone: 'cyan', icon: 'receipt' },
    { id: 'gross-sales', label: 'Gross sales', value: '$186,420.80', change: '+15.2%', note: 'before adjustments', tone: 'green', icon: 'dollar' },
    { id: 'net-sales', label: 'Net sales', value: '$172,840.30', change: '+11.6%', note: 'after returns & voids', tone: 'mint', icon: 'trend' },
    { id: 'commission', label: 'Commission', value: '$24,860.40', change: '+9.6%', note: 'approved this period', tone: 'purple', icon: 'coins' },
    { id: 'conversion', label: 'Conversion', value: '2.6%', change: '+0.3%', note: 'click-to-order rate', tone: 'sky', icon: 'chart' },
    { id: 'total-payout', label: 'Total payout', value: '$31,280.40', change: '+7.9%', note: 'commission + fees', tone: 'orange', icon: 'wallet' },
  ],
  partnerPerformance: [
    { id: 'partner-alpha', name: 'Partner Alpha', type: 'Publisher', amount: '$6,845.20', percent: 100, trend: '+18.4%', orders: '214' },
    { id: 'partner-beta', name: 'Partner Beta', type: 'Publisher', amount: '$5,126.80', percent: 75, trend: '+12.1%', orders: '186' },
    { id: 'partner-gamma', name: 'Partner Gamma', type: 'Influencer', amount: '$4,382.10', percent: 64, trend: '+7.8%', orders: '142' },
    { id: 'partner-delta', name: 'Partner Delta', type: 'Publisher', amount: '$3,614.60', percent: 53, trend: '+4.6%', orders: '118' },
    { id: 'partner-epsilon', name: 'Partner Epsilon', type: 'Influencer', amount: '$2,906.40', percent: 42, trend: '+2.9%', orders: '96' },
  ],
  commission: {
    total: '$49.7K',
    approved: { label: 'Approved', value: '$24,860', percent: 46, tone: 'green' },
    pending: { label: 'Pending approval', value: '$6,420', percent: 13, tone: 'orange' },
    paid: { label: 'Total paid', value: '$18,440', percent: 37, tone: 'blue' },
    voided: { label: 'Voided', value: '$1,280', percent: 4, tone: 'pink' },
  },
  partnerStatus: [
    { id: 'active', label: 'Active partners', value: 42, percent: 78, tone: 'green' },
    { id: 'applications', label: 'Applications pending', value: 12, percent: 22, tone: 'orange' },
    { id: 'invited', label: 'Invitations sent', value: 8, percent: 15, tone: 'blue' },
  ],
};

const thirtyDaySnapshot = {
  metrics: [
    { id: 'clicks', label: 'Clicks', value: '182,940', change: '+16.4%', note: 'vs previous period', tone: 'blue', icon: 'cursor' },
    { id: 'orders', label: 'Orders', value: '4,982', change: '+13.1%', note: 'completed orders', tone: 'cyan', icon: 'receipt' },
    { id: 'gross-sales', label: 'Gross sales', value: '$724,680.10', change: '+18.2%', note: 'before adjustments', tone: 'green', icon: 'dollar' },
    { id: 'net-sales', label: 'Net sales', value: '$681,240.70', change: '+14.4%', note: 'after returns & voids', tone: 'mint', icon: 'trend' },
    { id: 'commission', label: 'Commission', value: '$96,420.80', change: '+12.8%', note: 'approved this period', tone: 'purple', icon: 'coins' },
    { id: 'conversion', label: 'Conversion', value: '2.7%', change: '+0.4%', note: 'click-to-order rate', tone: 'sky', icon: 'chart' },
    { id: 'total-payout', label: 'Total payout', value: '$121,840.50', change: '+10.6%', note: 'commission + fees', tone: 'orange', icon: 'wallet' },
  ],
  partnerPerformance: [
    { id: 'partner-alpha', name: 'Partner Alpha', type: 'Publisher', amount: '$21,340.90', percent: 100, trend: '+20.6%', orders: '684' },
    { id: 'partner-beta', name: 'Partner Beta', type: 'Publisher', amount: '$16,820.40', percent: 79, trend: '+14.8%', orders: '596' },
    { id: 'partner-gamma', name: 'Partner Gamma', type: 'Influencer', amount: '$13,280.10', percent: 62, trend: '+11.2%', orders: '452' },
    { id: 'partner-delta', name: 'Partner Delta', type: 'Publisher', amount: '$10,460.80', percent: 49, trend: '+8.6%', orders: '390' },
    { id: 'partner-epsilon', name: 'Partner Epsilon', type: 'Influencer', amount: '$8,620.30', percent: 40, trend: '+5.4%', orders: '316' },
  ],
  commission: {
    total: '$194.2K',
    approved: { label: 'Approved', value: '$96,420', percent: 46, tone: 'green' },
    pending: { label: 'Pending approval', value: '$28,180', percent: 15, tone: 'orange' },
    paid: { label: 'Total paid', value: '$69,600', percent: 35, tone: 'blue' },
    voided: { label: 'Voided', value: '$4,280', percent: 4, tone: 'pink' },
  },
  partnerStatus: [
    { id: 'active', label: 'Active partners', value: 48, percent: 71, tone: 'green' },
    { id: 'applications', label: 'Applications pending', value: 16, percent: 24, tone: 'orange' },
    { id: 'invited', label: 'Invitations sent', value: 11, percent: 16, tone: 'blue' },
  ],
};

const ninetyDaySnapshot = {
  metrics: [
    { id: 'clicks', label: 'Clicks', value: '526,840', change: '+21.2%', note: 'vs previous period', tone: 'blue', icon: 'cursor' },
    { id: 'orders', label: 'Orders', value: '14,620', change: '+17.6%', note: 'completed orders', tone: 'cyan', icon: 'receipt' },
    { id: 'gross-sales', label: 'Gross sales', value: '$2.18M', change: '+24.9%', note: 'before adjustments', tone: 'green', icon: 'dollar' },
    { id: 'net-sales', label: 'Net sales', value: '$2.05M', change: '+20.3%', note: 'after returns & voids', tone: 'mint', icon: 'trend' },
    { id: 'commission', label: 'Commission', value: '$286.4K', change: '+19.8%', note: 'approved this period', tone: 'purple', icon: 'coins' },
    { id: 'conversion', label: 'Conversion', value: '2.8%', change: '+0.5%', note: 'click-to-order rate', tone: 'sky', icon: 'chart' },
    { id: 'total-payout', label: 'Total payout', value: '$362.8K', change: '+18.1%', note: 'commission + fees', tone: 'orange', icon: 'wallet' },
  ],
  partnerPerformance: [
    { id: 'partner-alpha', name: 'Partner Alpha', type: 'Publisher', amount: '$64,280.30', percent: 100, trend: '+24.2%', orders: '2,140' },
    { id: 'partner-beta', name: 'Partner Beta', type: 'Publisher', amount: '$51,620.40', percent: 80, trend: '+19.6%', orders: '1,864' },
    { id: 'partner-gamma', name: 'Partner Gamma', type: 'Influencer', amount: '$42,180.10', percent: 66, trend: '+16.2%', orders: '1,420' },
    { id: 'partner-delta', name: 'Partner Delta', type: 'Publisher', amount: '$32,460.80', percent: 50, trend: '+12.5%', orders: '1,080' },
    { id: 'partner-epsilon', name: 'Partner Epsilon', type: 'Influencer', amount: '$26,820.30', percent: 42, trend: '+9.6%', orders: '860' },
  ],
  commission: {
    total: '$582.8K',
    approved: { label: 'Approved', value: '$286,420', percent: 45, tone: 'green' },
    pending: { label: 'Pending approval', value: '$82,180', percent: 14, tone: 'orange' },
    paid: { label: 'Total paid', value: '$214,200', percent: 37, tone: 'blue' },
    voided: { label: 'Voided', value: '$11,280', percent: 4, tone: 'pink' },
  },
  partnerStatus: [
    { id: 'active', label: 'Active partners', value: 58, percent: 70, tone: 'green' },
    { id: 'applications', label: 'Applications pending', value: 21, percent: 25, tone: 'orange' },
    { id: 'invited', label: 'Invitations sent', value: 15, percent: 18, tone: 'blue' },
  ],
};

export const dashboardData = {
  workspace: {
    organization: 'YeahPromos',
    brand: 'Demo Brand',
    store: 'Demo Store',
    role: 'Demo Admin',
    currency: 'USD',
    timezone: 'America/Los_Angeles',
  },
  periods: [
    { id: '7d', label: 'May 05 – May 12, 2025', shortLabel: 'Last 7 days', snapshot: sevenDaySnapshot },
    { id: '30d', label: 'Apr 13 – May 12, 2025', shortLabel: 'Last 30 days', snapshot: thirtyDaySnapshot },
    { id: '90d', label: 'Feb 12 – May 12, 2025', shortLabel: 'Last 90 days', snapshot: ninetyDaySnapshot },
  ],
  navigation: [
    { id: 'overview', label: 'Overview', icon: 'grid' },
    {
      id: 'recruitment',
      label: 'Recruitment & Partners',
      icon: 'users',
      children: [
        { id: 'discover-influencers', label: 'Discover influencers' },
        { id: 'discover-publishers', label: 'Discover publishers' },
        { id: 'my-partners', label: 'My partners' },
        { id: 'applications', label: 'Applications' },
        { id: 'invite-history', label: 'Invite history' },
      ],
    },
    {
      id: 'campaigns',
      label: 'Campaigns',
      icon: 'chart',
      children: [
        { id: 'all-campaigns', label: 'All campaigns' },
        { id: 'affiliate-programs', label: 'Affiliate programs' },
        { id: 'influencer-campaigns', label: 'Influencer campaigns' },
      ],
    },
    {
      id: 'products-assets',
      label: 'Products & Assets',
      icon: 'bag',
      children: [
        { id: 'product-feed', label: 'Product feed' },
        { id: 'coupons', label: 'Coupons' },
        { id: 'banners-images', label: 'Banners & images' },
        { id: 'texts-emails', label: 'Texts & emails' },
      ],
    },
    {
      id: 'commission-rules',
      label: 'Commission & Rules',
      icon: 'coins',
      children: [
        { id: 'commission-rules-list', label: 'Commission rules' },
        { id: 'attribution-rules', label: 'Attribution rules' },
        { id: 'commission-invoices', label: 'Invoices' },
      ],
    },
    {
      id: 'data-transactions',
      label: 'Data & Transactions',
      icon: 'trend',
      children: [
        { id: 'performance', label: 'Performance' },
        { id: 'performance-brand', label: 'Performance by brand' },
        { id: 'transactions', label: 'Transactions' },
        { id: 'amazon-brb', label: 'Amazon BRB' },
      ],
    },
    {
      id: 'finance',
      label: 'Finance',
      icon: 'wallet',
      children: [
        { id: 'balance-payments', label: 'Balance & payments' },
        { id: 'finance-transactions', label: 'Transactions' },
        { id: 'payouts', label: 'Payouts' },
        { id: 'invoices', label: 'Invoices' },
        { id: 'payment-methods', label: 'Payment methods' },
      ],
    },
    {
      id: 'messages',
      label: 'Messages & Notifications',
      icon: 'message',
      children: [
        { id: 'all-messages', label: 'All Messages' },
        { id: 'partner-messages', label: 'Partner Messages' },
        { id: 'system-alerts', label: 'System Alerts' },
        { id: 'archived-messages', label: 'Archived' },
      ],
    },
    {
      id: 'settings',
      label: 'Integrations & Settings',
      icon: 'settings',
      children: [
        { id: 'team-accounts', label: 'Team accounts' },
        { id: 'permissions', label: 'Permissions' },
        { id: 'brand-integration', label: 'Brand integration' },
        { id: 'api-credentials', label: 'API credentials' },
      ],
    },
  ],
  ...sevenDaySnapshot,
  lastUpdated: '4 min ago',
  actionItems: [
    {
      id: 'application-review',
      icon: 'users',
      tone: 'blue',
      eyebrow: 'Partner applications',
      title: '12 applications need review',
      description: 'New publisher channels are waiting for approval.',
      meta: '12 pending',
      action: 'Review applications',
      navigationId: 'applications',
    },
    {
      id: 'product-sync',
      icon: 'bag',
      tone: 'orange',
      eyebrow: 'Product feed sync',
      title: '3 products failed to sync',
      description: 'Review the ASIN errors before the next campaign launch.',
      meta: 'Sync failed',
      action: 'View errors',
      navigationId: 'product-feed',
    },
    {
      id: 'campaign-launch',
      icon: 'chart',
      tone: 'purple',
      eyebrow: 'Campaigns',
      title: 'Summer Sale starts in 5 days',
      description: 'Confirm offers, creatives and partner access before launch.',
      meta: 'Scheduled',
      action: 'Open campaign',
      navigationId: 'all-campaigns',
    },
    {
      id: 'transaction-approval',
      icon: 'receipt',
      tone: 'green',
      eyebrow: 'Transactions',
      title: '28 transactions are ready for approval',
      description: 'Approve or void transactions with a reason and audit trail.',
      meta: '28 pending',
      action: 'Review transactions',
      navigationId: 'transactions',
    },
  ],
  quickActions: [
    { id: 'invite-partner', icon: 'send', label: 'Invite partner', navigationId: 'invite-history' },
    { id: 'create-campaign', icon: 'chart', label: 'Create campaign', navigationId: 'all-campaigns' },
    { id: 'add-product', icon: 'bag', label: 'Add product', navigationId: 'product-feed' },
    { id: 'add-coupon', icon: 'tag', label: 'Add coupon', navigationId: 'coupons' },
    { id: 'export-report', icon: 'download', label: 'Export report', navigationId: 'performance' },
  ],
  partners: [
    {
      id: 'northstar',
      name: 'Alpha Media',
      type: 'Publisher',
      channel: 'Content/Blog',
      status: 'Active',
      group: 'Premium publishers',
      audience: '1.2M monthly visits',
      commission: '$2,812.45',
    },
  ],
};


export const campaignPageData = {
  metrics: [
    { id: 'active-campaigns', label: 'Active campaigns', value: '18', change: '↑ 12.5%', note: 'vs Apr 28 – May 04', icon: 'users', sparkline: '0,26 12,18 25,31 37,16 48,25 60,10 71,17 84,12 96,6' },
    { id: 'click-throughs', label: 'Click-throughs', value: '282,401', change: '↑ 8.2%', note: 'vs Apr 28 – May 04', icon: 'cursor', sparkline: '0,25 12,18 25,31 36,17 48,24 60,7 72,14 84,4 96,10' },
    { id: 'campaign-orders', label: 'Orders', value: '6,521', change: '↑ 11.6%', note: 'vs Apr 28 – May 04', icon: 'receipt', sparkline: '0,23 12,16 24,29 36,19 47,26 60,9 70,15 84,5 96,9' },
    { id: 'campaign-sales', label: 'Sales', value: '$327,128.54', change: '↑ 9.7%', note: 'vs Apr 28 – May 04', icon: 'dollar', sparkline: '0,26 12,21 24,29 36,11 48,23 60,7 71,15 84,4 96,8' },
  ],
  campaigns: [
    {
      id: 'spring-collection-promo',
      name: 'Spring Collection Promo',
      code: 'CMP-2024-0001',
      type: 'Co-op',
      typeIcon: 'users',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Active',
      statusDetail: 'On track',
      stage: 'Execution',
      partners: '24',
      sales: '$62,845.22',
      orders: '32 orders',
      progress: 68,
      nextAction: 'Review assets',
      nextActionIcon: 'calendar',
      updated: 'May 16, 2025',
      updatedBy: 'Demo Owner A',
    },
    {
      id: 'tech-essentials-launch',
      name: 'Tech Essentials Launch',
      code: 'CMP-2024-0002',
      type: 'MDF',
      typeIcon: 'coins',
      channel: 'Influencer',
      channelIcon: 'users',
      status: 'Pending',
      statusDetail: 'Awaiting approval',
      stage: 'Review',
      partners: '18',
      sales: '$44,318.19',
      orders: '892 orders',
      progress: 15,
      nextAction: 'Approve budget',
      nextActionIcon: 'users',
      updated: 'May 15, 2025',
      updatedBy: 'Demo Owner B',
    },
    {
      id: 'mothers-day-special',
      name: "Mother's Day Special",
      code: 'CMP-2024-0003',
      type: 'Event',
      typeIcon: 'calendar',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Completed',
      statusDetail: 'Completed',
      stage: 'Complete',
      partners: '36',
      sales: '$38,912.46',
      orders: '768 orders',
      progress: 100,
      nextAction: 'No action required',
      nextActionIcon: 'check',
      updated: 'May 10, 2025',
      updatedBy: 'Demo Owner A',
    },
    {
      id: 'summer-sale-kickoff',
      name: 'Summer Sale Kickoff',
      code: 'CMP-2024-0004',
      type: 'Enablement',
      typeIcon: 'bag',
      channel: 'Publisher',
      channelIcon: 'send',
      status: 'Paused',
      statusDetail: 'Paused',
      stage: 'Execution',
      partners: '21',
      sales: '$28,433.71',
      orders: '543 orders',
      progress: 40,
      nextAction: 'Resume campaign',
      nextActionIcon: 'arrow',
      updated: 'May 9, 2025',
      updatedBy: 'Demo Owner B',
    },
    {
      id: 'back-to-school',
      name: 'Back to School',
      code: 'CMP-2024-0005',
      type: 'Co-op',
      typeIcon: 'users',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Draft',
      statusDetail: 'In planning',
      stage: 'Planning',
      partners: '12',
      sales: '$21,247.88',
      orders: '412 orders',
      progress: 30,
      nextAction: 'Add campaign assets',
      nextActionIcon: 'bag',
      updated: 'May 8, 2025',
      updatedBy: 'Demo Owner C',
    },
    {
      id: 'holiday-gift-guide',
      name: 'Holiday Gift Guide',
      code: 'CMP-2024-0006',
      type: 'MDF',
      typeIcon: 'coins',
      channel: 'Influencer',
      channelIcon: 'users',
      status: 'Closed',
      statusDetail: 'Completed',
      stage: 'Complete',
      partners: '15',
      sales: '$0',
      orders: '0 orders',
      progress: 100,
      nextAction: 'No action required',
      nextActionIcon: 'check',
      updated: 'May 6, 2025',
      updatedBy: 'Demo Owner C',
    },
    {
      id: 'brand-awareness-q2',
      name: 'Brand Awareness Q2',
      code: 'CMP-2024-0007',
      type: 'Event',
      typeIcon: 'calendar',
      channel: 'Publisher',
      channelIcon: 'send',
      status: 'Active',
      statusDetail: 'On track',
      stage: 'Execution',
      partners: '31',
      sales: '$33,614.93',
      orders: '678 orders',
      progress: 52,
      nextAction: 'Confirm attendance',
      nextActionIcon: 'calendar',
      updated: 'May 5, 2025',
      updatedBy: 'Demo Owner A',
    },
    {
      id: 'flash-sale-weekend',
      name: 'Flash Sale Weekend',
      code: 'CMP-2024-0008',
      type: 'Enablement',
      typeIcon: 'bag',
      channel: 'Affiliate',
      channelIcon: 'users',
      status: 'Completed',
      statusDetail: 'Completed',
      stage: 'Complete',
      partners: '9',
      sales: '$15,362.15',
      orders: '312 orders',
      progress: 100,
      nextAction: 'No action required',
      nextActionIcon: 'check',
      updated: 'May 4, 2025',
      updatedBy: 'Demo Owner B',
    },
  ],
};

export const attributionPageData = {
  models: [
    {
      id: 'data-driven',
      label: 'Data-driven (recommended)',
      summaryLabel: 'Data-driven model',
      description: 'Data-driven model analyzes historical performance to determine the optimal credit distribution across touchpoints.',
    },
    {
      id: 'last-click',
      label: 'Last-click',
      summaryLabel: 'Last-click model',
      description: 'Last-click model assigns conversion credit to the final eligible touchpoint before purchase.',
    },
    {
      id: 'first-click',
      label: 'First-click',
      summaryLabel: 'First-click model',
      description: 'First-click model assigns conversion credit to the first eligible touchpoint in the journey.',
    },
    {
      id: 'linear',
      label: 'Linear',
      summaryLabel: 'Linear model',
      description: 'Linear model distributes conversion credit evenly across eligible touchpoints.',
    },
    {
      id: 'position-based',
      label: 'Position-based (U-shape)',
      summaryLabel: 'Position-based model',
      description: 'Position-based model gives more credit to the first and last eligible touchpoints.',
    },
  ],
  activeModel: 'data-driven',
  summary: {
    assistedRevenue: '$128,430.76',
    trackingCoverage: '88.7%',
  },
  distribution: [
    { id: 'last-click', label: 'Last-click', value: 40, icon: 'users', tone: 'coral' },
    { id: 'direct-publisher', label: 'Direct publisher', value: 30, icon: 'send', tone: 'orange' },
    { id: 'influencer', label: 'Influencer', value: 20, icon: 'star', tone: 'purple' },
    { id: 'paid-media', label: 'Paid media', value: 10, icon: 'trend', tone: 'blue' },
  ],
  rules: [
    { id: 'main-website-blog', name: 'Main Website & Blog', channelType: 'Publisher', channelTone: 'publisher', logic: 'Last-click within channel', lookback: '30 days', priority: 1, status: 'Active' },
    { id: 'partner-content-reviews', name: 'Partner Content & Reviews', channelType: 'Publisher', channelTone: 'publisher', logic: 'Data-driven (weighted)', lookback: '30 days', priority: 2, status: 'Active' },
    { id: 'influencer-social-traffic', name: 'Influencer Social Traffic', channelType: 'Influencer', channelTone: 'influencer', logic: 'First-click within channel', lookback: '14 days', priority: 3, status: 'Active' },
    { id: 'influencer-promo-codes', name: 'Influencer Promo Codes', channelType: 'Influencer', channelTone: 'influencer', logic: 'Last-click within channel', lookback: '30 days', priority: 4, status: 'Active' },
    { id: 'paid-search-campaigns', name: 'Paid Search Campaigns', channelType: 'Paid', channelTone: 'paid', logic: 'Last-click', lookback: '7 days', priority: 5, status: 'Active' },
    { id: 'paid-social-campaigns', name: 'Paid Social Campaigns', channelType: 'Paid', channelTone: 'paid', logic: 'Position-based (U-shape)', lookback: '7 days', priority: 6, status: 'Active' },
  ],
  audit: [
    { id: 'lookback-update', date: 'May 12, 2025, 10:24 AM', title: 'Updated lookback window for Influencer Social Traffic', by: 'Demo Admin' },
    { id: 'paid-social-rule', date: 'May 9, 2025, 3:18 PM', title: 'Added rule: Paid Social Campaigns', by: 'Demo Admin' },
    { id: 'model-change', date: 'May 5, 2025, 9:41 AM', title: 'Changed attribution model to Data-driven', by: 'Demo Admin' },
    { id: 'initial-rules', date: 'Apr 28, 2025, 2:11 PM', title: 'Initial attribution rules created', by: 'Demo Admin' },
  ],
};

export const commissionRulesPageData = {
  metrics: [
    { id: 'active-rules', label: 'Active rules', value: '18', note: '12 added this month', icon: 'check', tone: 'coral' },
    { id: 'partners-covered', label: 'Partners covered', value: '1,248', note: '↑ 82% of total partners', icon: 'users', tone: 'purple' },
    { id: 'pending-changes', label: 'Pending changes', value: '3', note: '↑ 2 awaiting approval', icon: 'receipt', tone: 'orange' },
  ],
  selectedRuleId: 'standard-content-commission',
  rules: [
    {
      id: 'standard-content-commission',
      ruleId: 'ID: 10234',
      name: 'Standard Content Commission',
      scopePrimary: 'All partners',
      scopeSecondary: 'All products',
      scopeSummary: 'All partners / All products',
      partnerType: 'All partners',
      channel: 'Affiliate',
      baseCommission: '8.00%',
      rate: '8.00%',
      unit: '%',
      bonusRate: '2.00%',
      bonusThreshold: 'Over $500',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'May 01, 2025',
      effectiveAt: '2025-05-01',
      lastUpdated: 'Apr 30, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'new-partner-boost',
      ruleId: 'ID: 10231',
      name: 'New Partner Boost',
      scopePrimary: 'New partners',
      scopeSecondary: 'All products',
      scopeSummary: 'New partners / All products',
      partnerType: 'New partners',
      channel: 'Affiliate',
      baseCommission: '10.00%',
      rate: '10.00%',
      unit: '%',
      bonusRate: '3.00%',
      bonusThreshold: 'Over $300',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'Apr 15, 2025',
      effectiveAt: '2025-04-15',
      lastUpdated: 'Apr 14, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'seasonal-sale-bonus',
      ruleId: 'ID: 10228',
      name: 'Seasonal Sale Bonus',
      scopePrimary: 'All partners',
      scopeSecondary: 'Sale collection',
      scopeSummary: 'All partners / Sale collection',
      partnerType: 'All partners',
      channel: 'Affiliate',
      baseCommission: '6.00%',
      rate: '6.00%',
      unit: '%',
      bonusRate: '5.00%',
      bonusThreshold: 'Over $400',
      attributionWindow: '7 days',
      attributionType: 'Click',
      duration: '7 days',
      effectiveDate: 'Apr 10, 2025',
      effectiveAt: '2025-04-10',
      lastUpdated: 'Apr 9, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'blog-content-partners',
      ruleId: 'ID: 10225',
      name: 'Blog & Content Partners',
      scopePrimary: 'Content / Blog',
      scopeSecondary: 'All products',
      scopeSummary: 'Content / Blog / All products',
      partnerType: 'Content / Blog',
      channel: 'Publisher',
      baseCommission: '9.00%',
      rate: '9.00%',
      unit: '%',
      bonusRate: '2.00%',
      bonusThreshold: 'Over $500',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'Mar 25, 2025',
      effectiveAt: '2025-03-25',
      lastUpdated: 'Mar 24, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'tech-review-partners',
      ruleId: 'ID: 10221',
      name: 'Tech Review Partners',
      scopePrimary: 'Technology',
      scopeSecondary: 'All products',
      scopeSummary: 'Technology / All products',
      partnerType: 'Technology',
      channel: 'Publisher',
      baseCommission: '7.00%',
      rate: '7.00%',
      unit: '%',
      bonusRate: '2.00%',
      bonusThreshold: 'Over $600',
      attributionWindow: '14 days',
      attributionType: 'Click',
      duration: '14 days',
      effectiveDate: 'Mar 20, 2025',
      effectiveAt: '2025-03-20',
      lastUpdated: 'Mar 19, 2025',
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'newsletter-partners',
      ruleId: 'ID: 10218',
      name: 'Newsletter Partners',
      scopePrimary: 'Email / Newsletter',
      scopeSecondary: 'All products',
      scopeSummary: 'Email / Newsletter / All products',
      partnerType: 'Email / Newsletter',
      channel: 'Email',
      baseCommission: '10.00%',
      rate: '10.00%',
      unit: '%',
      bonusRate: '1.00%',
      bonusThreshold: 'Over $250',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'Mar 10, 2025',
      effectiveAt: '2025-03-10',
      lastUpdated: 'Mar 9, 2025',
      status: 'Scheduled',
      statusTone: 'scheduled',
    },
    {
      id: 'inactive-old-rules',
      ruleId: 'ID: 10198',
      name: 'Inactive – Old Rules',
      scopePrimary: 'All partners',
      scopeSecondary: 'All products',
      scopeSummary: 'All partners / All products',
      partnerType: 'All partners',
      channel: 'Affiliate',
      baseCommission: '5.00%',
      rate: '5.00%',
      unit: '%',
      bonusRate: '—',
      bonusThreshold: '',
      attributionWindow: '30 days',
      attributionType: 'Click',
      duration: '30 days',
      effectiveDate: 'Feb 01, 2025',
      effectiveAt: '2025-02-01',
      lastUpdated: 'Jan 31, 2025',
      status: 'Inactive',
      statusTone: 'inactive',
    },
    {
      id: 'black-friday-bonus',
      ruleId: 'ID: 10176',
      name: 'Black Friday Bonus',
      scopePrimary: 'All partners',
      scopeSecondary: 'BF collection',
      scopeSummary: 'All partners / BF collection',
      partnerType: 'All partners',
      channel: 'Affiliate',
      baseCommission: '8.00%',
      rate: '8.00%',
      unit: '%',
      bonusRate: '6.00%',
      bonusThreshold: 'Over $500',
      attributionWindow: '7 days',
      attributionType: 'Click',
      duration: '7 days',
      effectiveDate: 'Nov 15, 2024',
      effectiveAt: '2024-11-15',
      lastUpdated: 'Nov 14, 2024',
      status: 'Expired',
      statusTone: 'expired',
    },
  ],
  details: {
    'standard-content-commission': {
      description: 'Applies to all partners across all products and channels.',
      scope: 'All partners · All products',
      attributionWindow: '30 days',
      attributionType: 'Click',
      effectiveDate: 'May 01, 2025',
      lastUpdated: 'Apr 30, 2025',
      updatedBy: 'Demo Admin',
      tiers: [
        { label: 'Tier 1', amount: '$0.00 – $199.99', base: '6.00%', bonus: '—' },
        { label: 'Tier 2', amount: '$200.00 – $499.99', base: '7.00%', bonus: '1.00%' },
        { label: 'Tier 3', amount: '$500.00 – $999.99', base: '8.00%', bonus: '2.00%' },
        { label: 'Tier 4', amount: '$1,000.00+', base: '9.00%', bonus: '3.00%' },
      ],
      conditions: [
        'Valid for Content / Blog, Technology, and Review partners',
        'Excludes coupon-based orders',
      ],
      performance: {
        period: 'May 01 – May 12, 2025',
        clicks: '12,842',
        conversions: '1,024',
        commission: '$1,248.36',
      },
    },
  },
};

export const financeBalancePageData = {
  demoOnly: true,
  summary: [
    { id: 'account-balance', label: 'Account balance', value: '$20,062.51', note: '↑ 8.7% vs last 7 days', icon: 'wallet', tone: 'coral', noteTone: 'positive' },
    { id: 'available-payout', label: 'Available for payout', value: '$16,724.38', note: '↑ 5.3% vs last 7 days', icon: 'dollar', tone: 'green', noteTone: 'positive' },
    { id: 'pending-commission', label: 'Pending commission', value: '$5,059.44', note: 'From in-progress transactions', icon: 'clock', tone: 'purple', noteTone: 'neutral' },
    { id: 'next-payout-date', label: 'Next payout date', value: 'May 15, 2025', note: 'In 3 days', icon: 'calendar', tone: 'orange', noteTone: 'neutral' },
    { id: 'primary-payout-method', label: 'Primary payout method', value: '•••• 0000', note: 'Visa · Expires 05/27', icon: 'card', tone: 'blue', noteTone: 'neutral' },
  ],
  trend: {
    periods: {
      '30d': {
        label: 'Last 30 days',
        points: [
          { label: 'Apr 15', value: 14982 },
          { label: 'Apr 18', value: 14262 },
          { label: 'Apr 21', value: 13900 },
          { label: 'Apr 23', value: 8700 },
          { label: 'Apr 25', value: 10500 },
          { label: 'Apr 27', value: 12100 },
          { label: 'Apr 29', value: 15300 },
          { label: 'Apr 30', value: 14600 },
          { label: 'May 02', value: 16300 },
          { label: 'May 05', value: 13600 },
          { label: 'May 07', value: 15800 },
          { label: 'May 10', value: 17650 },
          { label: 'May 12', value: 20062 },
        ],
        tooltip: { index: 7, value: '$18,645.23' },
        yAxis: ['$25K', '$20K', '$15K', '$10K', '$5K', '$0'],
        xAxis: ['Apr 15', 'Apr 20', 'Apr 25', 'Apr 30', 'May 05', 'May 10'],
      },
      '90d': {
        label: 'Last 90 days',
        points: [
          { label: 'Feb 15', value: 11800 },
          { label: 'Mar 01', value: 12750 },
          { label: 'Mar 15', value: 13400 },
          { label: 'Apr 01', value: 14600 },
          { label: 'Apr 15', value: 14982 },
          { label: 'May 01', value: 17600 },
          { label: 'May 12', value: 20062 },
        ],
        tooltip: { index: 4, value: '$18,645.23' },
        yAxis: ['$25K', '$20K', '$15K', '$10K', '$5K', '$0'],
        xAxis: ['Feb 15', 'Mar 01', 'Mar 15', 'Apr 01', 'Apr 15', 'May 12'],
      },
      year: {
        label: 'This year',
        points: [
          { label: 'Jan', value: 9800 },
          { label: 'Feb', value: 11800 },
          { label: 'Mar', value: 13400 },
          { label: 'Apr', value: 14982 },
          { label: 'May', value: 20062 },
        ],
        tooltip: { index: 3, value: '$18,645.23' },
        yAxis: ['$25K', '$20K', '$15K', '$10K', '$5K', '$0'],
        xAxis: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
      },
    },
    openingBalance: '$14,982.23',
    totalCredits: '$37,842.19',
    totalDebits: '-$32,761.91',
    closingBalance: '$20,062.51',
  },
  payoutSchedule: [
    { date: 'May 15, 2025', relative: 'In 3 days', amount: '$12,450.00', status: 'Scheduled', tone: 'scheduled' },
    { date: 'May 29, 2025', relative: 'In 17 days', amount: '$11,200.00', status: 'Scheduled', tone: 'scheduled' },
    { date: 'Jun 12, 2025', relative: 'In 31 days', amount: '$10,800.00', status: 'Scheduled', tone: 'scheduled' },
  ],
  paymentMethods: [
    { id: 'visa-demo', brand: 'Visa', masked: '•••• 0000', expiry: 'Expires 05/27', primary: true, brandTone: 'visa' },
    { id: 'mastercard-demo', brand: 'Mastercard', masked: '•••• 1111', expiry: 'Expires 03/26', primary: false, brandTone: 'mastercard' },
    { id: 'bank-demo', brand: 'Bank transfer', masked: '•••• 2222', expiry: 'Checking account', primary: false, brandTone: 'bank' },
  ],
  recentPayouts: [
    { id: 'PAYOUT-DEMO-0415', date: 'Apr 30, 2025 09:12 AM', amount: '$12,450.00', method: 'Visa · •••• 0000', methodTone: 'visa', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-7X9L2' },
    { id: 'PAYOUT-DEMO-0331', date: 'Apr 15, 2025 09:08 AM', amount: '$11,680.00', method: 'Visa · •••• 0000', methodTone: 'visa', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-2J9P4' },
    { id: 'PAYOUT-DEMO-0317', date: 'Mar 31, 2025 09:04 AM', amount: '$10,950.00', method: 'Mastercard · •••• 1111', methodTone: 'mastercard', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-9M2D8' },
    { id: 'PAYOUT-DEMO-0303', date: 'Mar 17, 2025 09:01 AM', amount: '$10,320.00', method: 'Bank · •••• 2222', methodTone: 'bank', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-4J1H6' },
    { id: 'PAYOUT-DEMO-0217', date: 'Mar 03, 2025 08:59 AM', amount: '$9,870.00', method: 'Bank · •••• 2222', methodTone: 'bank', status: 'Paid', description: 'Bi-weekly payout', reference: 'DEMO-7P5Q1' },
  ],
};

export const helpCenterPageData = {
  demoOnly: true,
  categories: [
    {
      id: 'getting-started',
      label: 'Getting started',
      description: 'New to the platform? Learn the basics and set up your account for success.',
      articles: 12,
      guides: 5,
      icon: 'rocket',
      tone: 'coral',
    },
    {
      id: 'partner-management',
      label: 'Partner management',
      description: 'Manage partners, review applications, and grow your affiliate network.',
      articles: 18,
      guides: 7,
      icon: 'users',
      tone: 'green',
    },
    {
      id: 'payments-reporting',
      label: 'Payments & reporting',
      description: 'Understand commissions, payouts, and performance reports.',
      articles: 14,
      guides: 6,
      icon: 'card',
      tone: 'purple',
    },
  ],
  articles: [
    {
      id: 'getting-started-with-yeahpromos',
      title: 'Getting started with YeahPromos',
      description: 'A step-by-step guide to set up your merchant account and launch your first program.',
      category: 'Getting started',
      updated: 'May 08, 2025',
      datetime: '2025-05-08',
    },
    {
      id: 'create-affiliate-program',
      title: 'How to create an affiliate program',
      description: 'Learn how to configure program settings, commission plans, and partner terms.',
      category: 'Getting started',
      updated: 'May 05, 2025',
      datetime: '2025-05-05',
    },
    {
      id: 'approve-partner-applications',
      title: 'Review and approve partner applications',
      description: 'How to review, approve, or decline applications from potential partners.',
      category: 'Partner management',
      updated: 'Apr 30, 2025',
      datetime: '2025-04-30',
    },
    {
      id: 'commissions-and-payouts',
      title: 'Understanding commissions and payouts',
      description: 'Learn how commissions are calculated, payouts are scheduled, and payment methods work.',
      category: 'Payments & reporting',
      updated: 'Apr 28, 2025',
      datetime: '2025-04-28',
    },
    {
      id: 'export-performance-reports',
      title: 'Generate and export performance reports',
      description: 'Create custom reports to track clicks, conversions, and earnings.',
      category: 'Payments & reporting',
      updated: 'Apr 26, 2025',
      datetime: '2025-04-26',
    },
    {
      id: 'invite-your-first-partner',
      title: 'Invite your first partner',
      description: 'Use partner discovery and invitations to build your first partner pipeline.',
      category: 'Partner management',
      updated: 'Apr 24, 2025',
      datetime: '2025-04-24',
    },
    {
      id: 'connect-your-store',
      title: 'Connect your store and verify tracking',
      description: 'Check your store connection, tracking provider, and first conversion signals.',
      category: 'Getting started',
      updated: 'Apr 22, 2025',
      datetime: '2025-04-22',
    },
    {
      id: 'read-performance-dashboard',
      title: 'Read your performance dashboard',
      description: 'Understand the metrics that explain partner activity, sales, and commission health.',
      category: 'Payments & reporting',
      updated: 'Apr 20, 2025',
      datetime: '2025-04-20',
    },
  ],
  systems: [
    { id: 'platform', label: 'Platform', status: 'Operational' },
    { id: 'partner-dashboard', label: 'Partner Dashboard', status: 'Operational' },
    { id: 'email-delivery', label: 'Email Delivery', status: 'Operational' },
    { id: 'payment-processing', label: 'Payment Processing', status: 'Operational' },
  ],
};

export const apiCredentialsPageData = {
  demoOnly: true,
  credentials: [
    {
      id: 'reporting-service',
      environment: 'live',
      name: 'Reporting Service Key',
      masked: '••••••••••••8d3f',
      createdBy: { initials: 'RA', name: 'Riley Anderson', detail: 'riley.anderson · demo account' },
      createdOn: 'May 12, 2025',
      createdTime: '10:24 AM',
      lastUsed: 'May 12, 2025',
      lastUsedTime: '10:24 AM',
      scopes: ['Reports', 'Performance'],
      extraScopes: 2,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'automation-worker',
      environment: 'live',
      name: 'Automation Worker',
      masked: '••••••••••••b7a2',
      createdBy: { initials: 'JS', name: 'Jamie Santos', detail: 'jamie.santos · demo account' },
      createdOn: 'May 08, 2025',
      createdTime: '03:15 PM',
      lastUsed: 'May 11, 2025',
      lastUsedTime: '11:47 PM',
      scopes: ['Transactions', 'Campaigns'],
      extraScopes: 1,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'finance-integration',
      environment: 'live',
      name: 'Finance Integration',
      masked: '••••••••••••f91c',
      createdBy: { initials: 'MW', name: 'Morgan White', detail: 'morgan.white · demo account' },
      createdOn: 'Apr 29, 2025',
      createdTime: '09:02 AM',
      lastUsed: 'May 10, 2025',
      lastUsedTime: '08:33 AM',
      scopes: ['Transactions', 'Payouts'],
      extraScopes: 0,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'data-exporter',
      environment: 'live',
      name: 'Data Exporter',
      masked: '••••••••••••3c19',
      createdBy: { initials: 'DL', name: 'Drew Lee', detail: 'drew.lee · demo account' },
      createdOn: 'Apr 21, 2025',
      createdTime: '02:41 PM',
      lastUsed: 'May 09, 2025',
      lastUsedTime: '01:12 PM',
      scopes: ['Reports', 'Data Export'],
      extraScopes: 0,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'legacy-app-access',
      environment: 'live',
      name: 'Legacy App Access',
      masked: '••••••••••••9e14',
      createdBy: { initials: 'SA', name: 'Sam Adams', detail: 'sam.adams · demo account' },
      createdOn: 'Mar 18, 2025',
      createdTime: '05:36 PM',
      lastUsed: 'Apr 25, 2025',
      lastUsedTime: '04:21 PM',
      scopes: ['Reports', 'Performance'],
      extraScopes: 0,
      status: 'Inactive',
      statusTone: 'inactive',
    },
    {
      id: 'sandbox-testing',
      environment: 'live',
      name: 'Sandbox Testing Key',
      masked: '••••••••••••d5f7',
      createdBy: { initials: 'TC', name: 'Taylor Chen', detail: 'taylor.chen · demo account' },
      createdOn: 'Feb 10, 2025',
      createdTime: '11:18 AM',
      lastUsed: 'Never',
      lastUsedTime: '',
      scopes: ['Test Data'],
      extraScopes: 0,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'test-reporting',
      environment: 'test',
      name: 'Test Reporting Key',
      masked: '••••••••••••1a42',
      createdBy: { initials: 'RA', name: 'Riley Anderson', detail: 'riley.anderson · demo account' },
      createdOn: 'May 02, 2025',
      createdTime: '09:18 AM',
      lastUsed: 'May 12, 2025',
      lastUsedTime: '09:46 AM',
      scopes: ['Reports', 'Test Data'],
      extraScopes: 1,
      status: 'Active',
      statusTone: 'active',
    },
    {
      id: 'test-automation',
      environment: 'test',
      name: 'Test Automation Worker',
      masked: '••••••••••••6e08',
      createdBy: { initials: 'JS', name: 'Jamie Santos', detail: 'jamie.santos · demo account' },
      createdOn: 'Apr 26, 2025',
      createdTime: '02:05 PM',
      lastUsed: 'May 07, 2025',
      lastUsedTime: '04:11 PM',
      scopes: ['Transactions', 'Test Data'],
      extraScopes: 0,
      status: 'Inactive',
      statusTone: 'inactive',
    },
  ],
  webhooks: [
    {
      id: 'order-events',
      label: 'Order Events',
      status: 'Active',
      statusTone: 'active',
      url: 'https://••••••••••••••••••••••••.com/webhook/order',
    },
    {
      id: 'payout-events',
      label: 'Payout Events',
      status: 'Active',
      statusTone: 'active',
      url: 'https://••••••••••••••••••••••••.com/webhook/payout',
    },
    {
      id: 'partner-events',
      label: 'Partner Events',
      status: 'Active',
      statusTone: 'active',
      url: 'https://••••••••••••••••••••••••.com/webhook/partner',
    },
    {
      id: 'campaign-events',
      label: 'Campaign Events',
      status: 'Inactive',
      statusTone: 'inactive',
      url: 'https://••••••••••••••••••••••••.com/webhook/campaign',
    },
  ],
};

export const commissionInvoicesPageData = {
  demoOnly: true,
  totalCount: 73,
  dateRanges: [
    { id: 'last-7d', label: 'May 05 – May 12, 2025' },
    { id: 'last-30d', label: 'Apr 13 – May 12, 2025' },
    { id: 'last-90d', label: 'Feb 12 – May 12, 2025' },
  ],
  filters: {
    paymentMethod: [
      { value: 'all', label: 'All methods' },
      { value: 'Account credits', label: 'Account credits' },
      { value: 'Credit card', label: 'Credit card' },
      { value: 'Bank transfer', label: 'Bank transfer' },
    ],
    paymentType: [
      { value: 'all', label: 'All types' },
      { value: 'Publisher payout', label: 'Publisher payout' },
      { value: 'Price plan fee', label: 'Price plan fee' },
      { value: 'Account deposit', label: 'Account deposit' },
    ],
    status: [
      { value: 'all', label: 'All statuses' },
      { value: 'Paid', label: 'Paid' },
      { value: 'Pending', label: 'Pending' },
      { value: 'Failed', label: 'Failed' },
    ],
    brand: [
      { value: 'all', label: 'All brands' },
      { value: 'PartnerBoost', label: 'PartnerBoost' },
      { value: 'PartnerMatic', label: 'PartnerMatic' },
      { value: 'Northstar Demo', label: 'Northstar Demo' },
    ],
  },
  rows: [
    { id: 'INV-250512-0712', date: 'May 12, 2025 14:32', brand: 'PartnerBoost', paymentMethod: 'Account credits', paymentType: 'Publisher payout', description: 'Auto charged commission balance', amount: '-$0.00', status: 'Paid', statusTone: 'paid' },
    { id: 'INV-250511-0611', date: 'May 11, 2025 22:18', brand: 'PartnerMatic', paymentMethod: 'Account credits', paymentType: 'Price plan fee', description: 'Fees for Standard Plan', amount: '-$50.00', status: 'Paid', statusTone: 'paid' },
    { id: 'INV-250510-0438', date: 'May 10, 2025 21:06', brand: 'PartnerMatic', paymentMethod: 'Account credits', paymentType: 'Price plan fee', description: 'Fees for Standard Plan', amount: '-$50.00', status: 'Paid', statusTone: 'paid' },
    { id: 'INV-250510-0437', date: 'May 10, 2025 21:06', brand: 'PartnerBoost', paymentMethod: 'Credit card', paymentType: 'Account deposit', description: 'Account balance top-up', amount: '$500.00', status: 'Paid', statusTone: 'paid' },
    { id: 'INV-250509-0315', date: 'May 09, 2025 18:42', brand: 'Northstar Demo', paymentMethod: 'Bank transfer', paymentType: 'Publisher payout', description: 'Bi-weekly partner payout', amount: '-$320.00', status: 'Pending', statusTone: 'pending' },
  ],
};

export const messagesPageData = {
  demoOnly: true,
  unreadCount: 8,
  tabs: [
    { id: 'all-messages', label: 'All Messages', count: 8 },
    { id: 'partner-messages', label: 'Partner Messages', count: 5 },
    { id: 'system-alerts', label: 'System Alerts', count: 2 },
    { id: 'archived-messages', label: 'Archived', count: null },
  ],
  filterOptions: [
    { value: 'all', label: 'All messages' },
    { value: 'unread', label: 'Unread only' },
    { value: 'partner', label: 'Partner messages' },
    { value: 'system', label: 'System alerts' },
  ],
  messages: [
    {
      id: 'message-alpha-media',
      sender: 'Alpha Media',
      initials: 'AM',
      avatarTone: 'rose',
      subject: 'Product collaboration proposal',
      preview: 'Hi Demo1 team, I’d love to discuss...',
      time: '10:24 AM',
      date: 'May 12, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: true,
    },
    {
      id: 'message-creative-bytes',
      sender: 'Creative Bytes',
      initials: 'CB',
      avatarTone: 'lavender',
      subject: 'Campaign content approval',
      preview: 'I’ve submitted the content for your...',
      time: '9:15 AM',
      date: 'May 12, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: true,
    },
    {
      id: 'message-future-hub',
      sender: 'Future Hub',
      initials: 'FH',
      avatarTone: 'blue',
      subject: 'Commission inquiry',
      preview: 'Could you confirm the commission...',
      time: 'Yesterday',
      date: 'May 11, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: false,
    },
    {
      id: 'message-system-payout',
      sender: 'System Alerts',
      initials: '!',
      avatarTone: 'alert',
      subject: 'Payout processed',
      preview: 'A payout of $2,431.25 has been...',
      time: 'Yesterday',
      date: 'May 11, 2025',
      category: 'system',
      kind: 'System Alert',
      unread: true,
    },
    {
      id: 'message-karma-collective',
      sender: 'Karma Collective',
      initials: 'KC',
      avatarTone: 'cyan',
      subject: 'Discount code request',
      preview: 'Hi, can we get a unique discount code...',
      time: 'May 11',
      date: 'May 11, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: false,
    },
    {
      id: 'message-partnerboost',
      sender: 'PartnerBoost Team',
      initials: 'PT',
      avatarTone: 'pink',
      subject: 'New feature: Campaign Auto-Invite',
      preview: 'We’re excited to announce a new...',
      time: 'May 10',
      date: 'May 10, 2025',
      category: 'partner',
      kind: 'Partner Message',
      unread: false,
    },
    {
      id: 'message-gocertify',
      sender: 'GoCertify',
      initials: 'G',
      avatarTone: 'peach',
      subject: 'Performance update',
      preview: 'Here’s your performance for Apr 28 – May 4...',
      time: 'May 09',
      date: 'May 09, 2025',
      category: 'system',
      kind: 'System Alert',
      unread: false,
    },
    {
      id: 'message-influencer-success',
      sender: 'Influencer Success',
      initials: 'IS',
      avatarTone: 'mint',
      subject: 'Welcome to YeahPromos!',
      preview: 'Welcome aboard! We’re here to help...',
      time: 'May 08',
      date: 'May 08, 2025',
      category: 'archived',
      kind: 'Partner Message',
      unread: false,
    },
  ],
  conversation: {
    messageId: 'message-alpha-media',
    subject: 'Product collaboration proposal',
    kind: 'Partner Message',
    sender: {
      name: 'Alpha Media',
      initials: 'AM',
      avatarTone: 'rose',
      email: 'support [at] alphamedia.example',
    },
    recipient: {
      name: 'Demo1',
      initials: 'D1',
      avatarTone: 'slate',
      email: 'brand [at] demo1.example',
    },
    sent: 'May 12, 2025 10:24 AM',
    body: [
      'Hi Demo1 team,',
      'I’d love to discuss a potential product collaboration for our upcoming summer campaign. Our audience aligns closely with your brand, and I believe this could be a great opportunity for both of us.',
      'Please let me know if you’re open to a quick call this week.',
      'Looking forward to your response!',
      'Best regards,',
      'Alpha Media Team',
    ],
    attachments: [
      { name: 'Collaboration_Proposal.pdf', type: 'PDF', size: '1.2 MB', icon: 'file', tone: 'pdf' },
      { name: 'Audience_Insights.xlsx', type: 'XLSX', size: '854 KB', icon: 'chart', tone: 'sheet' },
      { name: 'Campaign_Moodboard.png', type: 'PNG', size: '2.4 MB', icon: 'file', tone: 'image' },
    ],
    replies: [
      { id: 'reply-demo1', sender: 'Demo1 (You)', initials: 'D1', avatarTone: 'slate', time: 'May 12, 2025 11:02 AM', body: 'Hi Alpha Media, thanks for reaching out! We’d be happy to explore this opportunity.\nAre you available for a call on Wednesday at 2 PM EST?' },
      { id: 'reply-alpha', sender: 'Alpha Media', initials: 'AM', avatarTone: 'rose', time: 'May 12, 2025 11:15 AM', body: 'Wednesday at 2 PM works great! I’ll send over a calendar invite.' },
    ],
  },
  partnerDetails: {
    name: 'Alpha Media',
    initials: 'AM',
    avatarTone: 'rose',
    location: 'United States',
    contact: 'contact [at] alphamedia.example',
    activeCampaigns: [
      { name: 'Summer Essentials 2025', dates: 'May 01 – May 31, 2025', status: 'Active' },
      { name: 'New Arrivals Launch', dates: 'Apr 15 – May 15, 2025', status: 'Active' },
    ],
    stats: [
      { label: 'Total Sales', value: '$24,812.45' },
      { label: 'Conversions', value: '1,246' },
      { label: 'Commission Earned', value: '$2,481.25' },
      { label: 'Pending Payout', value: '$1,120.00' },
    ],
    conversationId: 'MSG-20250512-1024',
    conversationStatus: 'Open',
    labels: '+',
    addedToCrm: 'Yes',
  },
};
