const page = (id, title, parent, description, kind) => ({ id, title, parent, description, kind });

export const operationsPages = [
  page('performance', 'Performance', 'Data & Transactions', 'Track how your affiliate program is performing across key metrics.', 'performance'),
  page('performance-brand', 'Performance by brand', 'Data & Transactions', 'Compare performance across brands, stores, and partner channels.', 'performance-brand'),
  page('transactions', 'Transactions', 'Data & Transactions', 'Review, approve, and export the transactions generated by your affiliate program.', 'transactions'),
  page('amazon-brb', 'Amazon BRB', 'Data & Transactions', 'Monitor Amazon brand referral performance and campaign-level product activity.', 'amazon-brb'),
  page('affiliate-programs', 'Affiliate programs', 'Campaigns', 'Create and manage your affiliate programs. Invite partners and track program performance.', 'affiliate-programs'),
  page('influencer-campaigns', 'Influencer campaigns', 'Campaigns', 'Create and manage influencer campaigns to grow your brand and drive measurable results.', 'influencer-campaigns'),
];

export const operationsPageIds = operationsPages.map(({ id }) => id);

const series = (label, values, display, color = 'brand') => ({
  label,
  display,
  color,
  points: values.map((value, index) => ({ label: ['May 05', 'May 06', 'May 07', 'May 08', 'May 09', 'May 10', 'May 11', 'May 12'][index], value })),
});

export const performanceSeries = {
  clicks: series('Clicks', [34200, 38500, 36200, 42900, 48800, 46200, 40400, 39900], 'count'),
  orders: series('Orders', [820, 940, 910, 1080, 1240, 1190, 1060, 1020], 'count'),
  commission: series('Commission', [21400, 24200, 22800, 27400, 31200, 29800, 26400, 25800], 'currency'),
  grossSales: series('Gross sales', [148000, 165000, 158000, 188000, 214000, 206000, 184000, 181000], 'currency'),
  netSales: series('Net sales', [138000, 155000, 149000, 178000, 203000, 196000, 175000, 172000], 'currency'),
  voids: series('Voids', [2800, 3200, 2900, 4100, 3600, 3300, 3800, 3100], 'currency'),
};

export const performanceMetricOptions = [
  ['clicks', 'Clicks'],
  ['orders', 'Orders'],
  ['commission', 'Commission'],
  ['grossSales', 'Gross sales'],
  ['netSales', 'Net sales'],
  ['voids', 'Voids'],
];

export const brandPerformanceRecords = [
  { id: 'northstar', brand: 'Northstar Labs', color: 'brand', clicks: '38,420', orders: '1,146', grossSales: '$86,420.20', commission: '$10,684.10', conversion: '2.98%' },
  { id: 'fieldhouse', brand: 'Fieldhouse Goods', color: 'ink', clicks: '26,810', orders: '842', grossSales: '$62,140.70', commission: '$7,286.50', conversion: '3.14%' },
  { id: 'canyon', brand: 'Canyon Home', color: 'success', clicks: '18,240', orders: '506', grossSales: '$42,680.40', commission: '$4,921.80', conversion: '2.77%' },
  { id: 'atlas', brand: 'Atlas Outdoor', color: 'warning', clicks: '12,604', orders: '318', grossSales: '$29,180.80', commission: '$3,414.90', conversion: '2.52%' },
];

export const transactionRecords = [
  { id: 'txn-1042', order: 'ORD-1042', partner: 'Alpha Media', brand: 'Northstar Labs', sku: 'NL-TRAIL-01', amount: '$428.00', commission: '$34.24', status: 'Pending', type: 'Sale', country: 'US', date: 'May 12, 2025 · 09:42' },
  { id: 'txn-1041', order: 'ORD-1041', partner: 'Future Hub', brand: 'Fieldhouse Goods', sku: 'FH-CANVAS-08', amount: '$286.50', commission: '$22.92', status: 'Paid', type: 'Sale', country: 'US', date: 'May 12, 2025 · 08:16' },
  { id: 'txn-1040', order: 'ORD-1040', partner: 'Gocertify', brand: 'Canyon Home', sku: 'CH-LAMP-02', amount: '$172.00', commission: '$13.76', status: 'Pending', type: 'Sale', country: 'CA', date: 'May 11, 2025 · 17:30' },
  { id: 'txn-1039', order: 'ORD-1039', partner: 'Creative Bytes', brand: 'Northstar Labs', sku: 'NL-JACKET-14', amount: '$640.00', commission: '$51.20', status: 'Paid', type: 'Sale', country: 'UK', date: 'May 11, 2025 · 14:02' },
  { id: 'txn-1038', order: 'ORD-1038', partner: 'Karma Collective', brand: 'Atlas Outdoor', sku: 'AO-PACK-03', amount: '$318.00', commission: '$25.44', status: 'Void', type: 'Return', country: 'US', date: 'May 11, 2025 · 11:46' },
  { id: 'txn-1037', order: 'ORD-1037', partner: 'The Dealroom', brand: 'Northstar Labs', sku: 'NL-TEE-06', amount: '$198.00', commission: '$15.84', status: 'Pending', type: 'Sale', country: 'AU', date: 'May 10, 2025 · 19:12' },
  { id: 'txn-1036', order: 'ORD-1036', partner: 'Shopper Edit', brand: 'Fieldhouse Goods', sku: 'FH-MUG-01', amount: '$74.00', commission: '$5.92', status: 'Paid', type: 'Sale', country: 'US', date: 'May 10, 2025 · 15:28' },
  { id: 'txn-1035', order: 'ORD-1035', partner: 'Daily Living', brand: 'Canyon Home', sku: 'CH-RUG-11', amount: '$520.00', commission: '$41.60', status: 'Pending', type: 'Sale', country: 'DE', date: 'May 10, 2025 · 10:08' },
];

export const amazonCampaignRecords = [
  { id: 'brb-summer', campaign: 'Summer Trail Essentials', status: 'Active', clicks: '18,420', detailViews: '12,840', carts: '4,320', purchases: '1,284', sales: '$68,420.40', date: 'May 01 – May 12' },
  { id: 'brb-home', campaign: 'Home Refresh Event', status: 'Active', clicks: '12,680', detailViews: '8,940', carts: '2,860', purchases: '842', sales: '$42,180.20', date: 'Apr 20 – May 12' },
  { id: 'brb-video', campaign: 'Video Creator Test', status: 'Draft', clicks: '4,210', detailViews: '2,806', carts: '684', purchases: '186', sales: '$9,620.80', date: 'May 08 – May 12' },
];

export const affiliateProgramRecords = [
  { id: 'program-general', name: 'General Affiliate Program', initials: 'GF', commission: '15%', attribution: '30 days', partners: '198', tags: ['Content/Blog', 'Coupons', 'Deal'], dateRange: 'Jan 01 – Dec 31, 2025', status: 'Active', tone: 'success', markTone: 'red' },
  { id: 'program-tech', name: 'Tech Content Partners', initials: 'TC', commission: '12%', attribution: '30 days', partners: '86', tags: ['Content/Blog', 'Review'], dateRange: 'Feb 01 – Dec 31, 2025', status: 'Active', tone: 'success', markTone: 'purple' },
  { id: 'program-deal', name: 'Deal & Savings Network', initials: 'DS', commission: '10%', attribution: '7 days', partners: '124', tags: ['Coupons', 'Deal'], dateRange: 'Jan 15 – Dec 31, 2025', status: 'Active', tone: 'success', markTone: 'red' },
  { id: 'program-onboarding', name: 'New Customer Onboarding', initials: 'NO', commission: '20%', attribution: '30 days', partners: '42', tags: ['Content/Blog'], dateRange: 'Mar 01 – Aug 31, 2025', status: 'Paused', tone: 'warning', markTone: 'green' },
  { id: 'program-influencer', name: 'Influencer Starter Program', initials: 'IN', commission: '18%', attribution: '14 days', partners: '26', tags: ['Social/Influencer'], dateRange: 'Apr 01 – Sep 30, 2025', status: 'Paused', tone: 'warning', markTone: 'blue' },
  { id: 'program-pr', name: 'PR & Media Partners', initials: 'PR', commission: '15%', attribution: '45 days', partners: '36', tags: ['Content/Blog'], dateRange: 'Jan 01 – Dec 31, 2025', status: 'Draft', tone: 'neutral', markTone: 'orange' },
];

export const influencerCampaignRecords = [
  { id: 'inf-skin', name: 'Summer Glow Skincare', category: 'Beauty & Personal Care', platforms: ['Instagram', 'TikTok'], creators: '32', deliverables: '4', budget: '$8,000', budgetPercent: 68, status: 'Live', tone: 'success', date: 'May 05 – May 22', dateRangeKey: 'May 05 – May 12, 2025', mark: 'SG', markTone: 'sand', avatar: { initials: 'SG', tone: 'sand' }, videos: [{ title: 'Glow routine', views: '18.4K', date: 'May 06', tone: 'sand', mark: 'GLOW' }, { title: 'Texture test', views: '12.8K', date: 'May 04', tone: 'linen', mark: 'TEST' }] },
  { id: 'inf-fitness', name: 'Fit & Strong Challenge', category: 'Health & Fitness', platforms: ['Instagram', 'TikTok'], creators: '45', deliverables: '6', budget: '$12,000', budgetPercent: 55, status: 'Live', tone: 'success', date: 'May 01 – May 28', dateRangeKey: 'May 05 – May 12, 2025', mark: 'FS', markTone: 'slate', avatar: { initials: 'FS', tone: 'slate' }, videos: [{ title: 'Challenge prep', views: '22.6K', date: 'May 03', tone: 'slate', mark: 'MOVE' }, { title: 'Workout recap', views: '16.9K', date: 'May 01', tone: 'blue', mark: 'RECAP' }] },
  { id: 'inf-spring', name: 'Spring Collection Launch', category: 'Fashion', platforms: ['Instagram', 'TikTok', 'YouTube'], creators: '28', deliverables: '5', budget: '$10,000', budgetPercent: 62, status: 'Live', tone: 'success', date: 'Apr 28 – May 20', dateRangeKey: 'Apr 28 – May 04, 2025', mark: 'SC', markTone: 'linen', avatar: { initials: 'SC', tone: 'linen' }, videos: [{ title: 'Spring lookbook', views: '31.2K', date: 'Apr 30', tone: 'linen', mark: 'LOOK' }, { title: 'New arrivals', views: '20.5K', date: 'Apr 28', tone: 'sand', mark: 'NEW' }] },
  { id: 'inf-work', name: 'Work From Anywhere', category: 'Tech & Electronics', platforms: ['YouTube', 'Instagram'], creators: '20', deliverables: '4', budget: '$6,500', budgetPercent: 31, status: 'Live', tone: 'success', date: 'Apr 20 – May 16', dateRangeKey: 'Apr 28 – May 04, 2025', mark: 'WA', markTone: 'sand', avatar: { initials: 'WA', tone: 'sand' }, videos: [{ title: 'Desk setup', views: '14.7K', date: 'Apr 25', tone: 'blue', mark: 'DESK' }, { title: 'Remote kit', views: '11.1K', date: 'Apr 22', tone: 'slate', mark: 'KIT' }] },
  { id: 'inf-beach', name: 'Summer Getaway', category: 'Travel', platforms: ['Instagram'], creators: '18', deliverables: '3', budget: '$7,000', budgetPercent: 44, status: 'Upcoming', tone: 'warning', date: 'Starts May 20, 2025', dateRangeKey: 'Apr 21 – Apr 27, 2025', mark: 'SG', markTone: 'blue', avatar: { initials: 'SG', tone: 'blue' }, videos: [{ title: 'Beach edit', views: '9.8K', date: 'May 20', tone: 'blue', mark: 'TRIP' }, { title: 'Travel diary', views: '7.4K', date: 'May 21', tone: 'linen', mark: 'DIARY' }] },
  { id: 'inf-eating', name: 'Clean Eating Week', category: 'Food & Beverage', platforms: ['Instagram', 'TikTok'], creators: '25', deliverables: '5', budget: '$5,000', budgetPercent: 0, status: 'Upcoming', tone: 'warning', date: 'Starts May 25, 2025', dateRangeKey: 'Apr 21 – Apr 27, 2025', mark: 'CE', markTone: 'green', avatar: { initials: 'CE', tone: 'green' }, videos: [{ title: 'Meal prep', views: '13.1K', date: 'May 25', tone: 'green', mark: 'PREP' }, { title: 'Week reset', views: '10.6K', date: 'May 26', tone: 'sand', mark: 'RESET' }] },
  { id: 'inf-camera', name: 'Capture The Moment', category: 'Photography', platforms: ['Instagram'], creators: '15', deliverables: '3', budget: '$3,500', budgetPercent: 0, status: 'Draft', tone: 'neutral', date: 'Last edited May 08, 2025', dateRangeKey: 'Apr 21 – Apr 27, 2025', mark: 'CM', markTone: 'slate', avatar: { initials: 'CM', tone: 'slate' }, videos: [{ title: 'Portrait tips', views: '8.4K', date: 'May 08', tone: 'slate', mark: 'TIPS' }, { title: 'Shoot notes', views: '6.9K', date: 'May 07', tone: 'linen', mark: 'NOTES' }] },
  { id: 'inf-home', name: 'Home Comforts', category: 'Home & Living', platforms: ['Instagram', 'YouTube'], creators: '22', deliverables: '4', budget: '$6,000', budgetPercent: 0, status: 'Draft', tone: 'neutral', date: 'Last edited Apr 28, 2025', dateRangeKey: 'Apr 21 – Apr 27, 2025', mark: 'HC', markTone: 'linen', avatar: { initials: 'HC', tone: 'linen' }, videos: [{ title: 'Home reset', views: '12.2K', date: 'Apr 28', tone: 'linen', mark: 'RESET' }, { title: 'Room edit', views: '9.5K', date: 'Apr 27', tone: 'green', mark: 'EDIT' }] },
  { id: 'inf-fragrance', name: 'Fragrance Favorites', category: 'Beauty & Personal Care', platforms: ['Instagram', 'TikTok'], creators: '30', deliverables: '5', budget: '$9,000', budgetPercent: 100, status: 'Completed', tone: 'neutral', date: 'Completed Apr 30, 2025', dateRangeKey: 'Apr 21 – Apr 27, 2025', mark: 'FF', markTone: 'sand', avatar: { initials: 'FF', tone: 'sand' }, videos: [{ title: 'Layering guide', views: '19.7K', date: 'Apr 30', tone: 'sand', mark: 'LAYER' }, { title: 'Scent story', views: '15.3K', date: 'Apr 29', tone: 'blue', mark: 'STORY' }] },
];

const stateKeyByPageId = {
  'performance-brand': 'performanceBrand',
  'amazon-brb': 'amazonBrb',
  'affiliate-programs': 'affiliatePrograms',
  'influencer-campaigns': 'influencerCampaigns',
};

export const getOperationsStateKey = (pageId) => stateKeyByPageId[pageId] ?? pageId;

export function getOperationsPage(pageId) {
  return operationsPages.find((item) => item.id === pageId) ?? null;
}

export function createOperationsState() {
  return {
    performance: { query: '', filters: { cadence: 'Daily', partner: 'All partners' }, selectedId: null, tab: 'clicks' },
    performanceBrand: { query: '', filters: { cadence: 'Daily', brand: 'All brands' }, selectedId: null, tab: 'clicks' },
    transactions: { query: '', filters: { status: 'All statuses', country: 'All countries', type: 'All types' }, selectedId: null, tab: 'all' },
    amazonBrb: { query: '', filters: { cadence: 'Daily', date: 'May 01 – May 12, 2025' }, selectedId: 'brb-summer', tab: 'clicks' },
    affiliatePrograms: { query: '', filters: { status: 'All statuses', sort: 'Recently updated' }, selectedId: null, filtersOpen: false, tab: 'all' },
    influencerCampaigns: { query: '', filters: { category: 'All categories', platform: 'All platforms', budget: 'Any budget', date: 'May 05 – May 12, 2025' }, selectedId: null, filtersOpen: false, tab: 'live' },
  };
}

export function filterOperationsRecords(records, { query = '', filters = {} } = {}) {
  const normalizedQuery = String(query ?? '').trim().toLowerCase();
  return records.filter((record) => {
    const searchable = Object.values(record).join(' ').toLowerCase();
    if (normalizedQuery && !searchable.includes(normalizedQuery)) return false;
    return Object.entries(filters).every(([key, expected]) => {
      if (!expected || /^all\b/i.test(String(expected))) return true;
      return String(record[key] ?? '').toLowerCase() === String(expected).toLowerCase();
    });
  });
}

const numericValue = (value) => Number(String(value ?? '').replace(/[^\d.]/g, '')) || 0;

export function sortAffiliateProgramRecords(records, sort = 'Recently updated') {
  const sorted = [...records];
  if (sort === 'Most partners') return sorted.sort((a, b) => numericValue(b.partners) - numericValue(a.partners));
  if (sort === 'Highest commission') return sorted.sort((a, b) => numericValue(b.commission) - numericValue(a.commission));
  return sorted;
}

export function filterInfluencerCampaignRecords(records, { query = '', filters = {}, tab = 'all' } = {}) {
  const normalizedQuery = String(query ?? '').trim().toLowerCase();
  const budget = String(filters.budget ?? '');
  return records.filter((record) => {
    const matchesQuery = !normalizedQuery || Object.values(record).join(' ').toLowerCase().includes(normalizedQuery);
    const matchesCategory = !filters.category || /^all\b/i.test(filters.category) || record.category === filters.category;
    const matchesPlatform = !filters.platform || /^all\b/i.test(filters.platform) || record.platforms.includes(filters.platform);
    const matchesTab = tab === 'all' || record.status.toLowerCase() === tab;
    const budgetValue = numericValue(record.budget);
    const matchesBudget = !budget || /^any\b/i.test(budget) || (budget === 'Under $5,000' && budgetValue < 5000) || (budget === '$5,000 – $10,000' && budgetValue >= 5000 && budgetValue <= 10000) || (budget === 'Over $10,000' && budgetValue > 10000);
    const matchesDate = !filters.date || filters.date === 'May 05 – May 12, 2025' || /^all\b/i.test(filters.date) || record.dateRangeKey === filters.date;
    return matchesQuery && matchesCategory && matchesPlatform && matchesTab && matchesBudget && matchesDate;
  });
}

function updatePageState(state, pageId, updater) {
  const key = getOperationsStateKey(pageId);
  if (!state[key]) return state;
  return { ...state, [key]: updater(state[key]) };
}

export function updateOperationsSearch(state, pageId, query) {
  return updatePageState(state, pageId, (pageState) => ({ ...pageState, query: String(query ?? '') }));
}

export function updateOperationsFilter(state, pageId, filterKey, value) {
  return updatePageState(state, pageId, (pageState) => ({ ...pageState, filters: { ...pageState.filters, [filterKey]: value } }));
}

export function selectOperationsRecord(state, pageId, recordId) {
  return updatePageState(state, pageId, (pageState) => ({ ...pageState, selectedId: recordId ?? null }));
}

export function toggleOperationsFilters(state, pageId) {
  return updatePageState(state, pageId, (pageState) => ({ ...pageState, filtersOpen: !pageState.filtersOpen }));
}

export function resetOperationsFilters(state, pageId) {
  const initialState = createOperationsState()[getOperationsStateKey(pageId)];
  if (!initialState) return state;
  return updatePageState(state, pageId, (pageState) => ({
    ...pageState,
    query: initialState.query,
    filters: { ...initialState.filters },
    selectedId: null,
    filtersOpen: false,
    tab: initialState.tab,
  }));
}

export function selectOperationsTab(state, pageId, tab) {
  return updatePageState(state, pageId, (pageState) => ({ ...pageState, tab: tab ?? pageState.tab }));
}
